### ISSUE TITLE
As an applicant I want to be able to check my information before submitting my application

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1009]
We have at least two requests for this feature:
- one from an applicant encountered during Front support
- a second from J at SF who said this is a frequent problem for people who fill out the form and the typos cause downstream problems with pulling records.

This would address #971, #996 and #170

Problems this would alleviate or solve:
- would lead to less duplicate applications
- would lead to less difficulty for public defenders to look up records with typos
- would lead to more reliable, well-formatted data
- would reduce applicant confusion and uncertainty about what they sent us
- would reduce bounced emails & texts caused by typos

Steps to solve:
- write a CountyApplicationReview view that uses a display form
- hook it up with the rest of the application workflow and make sure it properly displays an applicant's info for them.
- change copy on form buttons in accordance with #971 & #996

**Comment by TiffanyAndrews** [comment]
As CfA staff, I don’t want emails or text messages to bounce 

As an org user, I don’t want to receive PII with typos because I need to use accurate information for pulling records. 

- Modify letter review page in the County application form flow
- adjust all behave tests to expect confirmation page step
- add a behave test for going “back” from confirmation page
- adjust text on buttons of other pages to account for new flow

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer add the mockups to this issue

**Comment by jazmynlatimer** [comment]
All mockups, content,  and Sketch files can be found here: https://drive.google.com/drive/u/0/folders/0B3BLnlbsdQ_hWFN3NmRuSFhPRWM

**Comment by jazmynlatimer** [comment]
Review page- desktop:
![b-desktop-review](https://user-images.githubusercontent.com/5255453/30885681-0eb07a08-a2c9-11e7-8c9c-7fc72c527d3c.png)


Review page - mobile:
![b-mobile-review](https://user-images.githubusercontent.com/5255453/30885683-11f3d778-a2c9-11e7-8eae-95a635940a70.png)


User clicked "edit" individual field:
![b-desktop-editfield](https://user-images.githubusercontent.com/5255453/30885688-157764be-a2c9-11e7-9fc6-e2e34658d981.png)


User clicked "edit submission"
![b-desktop-editpg](https://user-images.githubusercontent.com/5255453/30885693-18c5b1b6-a2c9-11e7-9081-53d920f3f47b.png)

**Comment by jazmynlatimer** [comment]
Note:
- you can use CMR styling of outlined "edit" buttons instead of the ones in this mockup
- language for flash messages are in this doc: https://docs.google.com/document/d/1ynKA4PMRoNcUZVp54ENlCW-s3ycmdwZVq03Q1RLj7CU/edit
