### ISSUE TITLE
Two possible applicants receiving an error on form pages

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1012]
**Errors found**
From audit hour, we found two times when it appeared that users received the error below while submitting a page in the application form. This happened on `/apply/` (county selection) and `/application/letter/`

![screen shot 2017-07-24 at 4 47 37 pm](https://user-images.githubusercontent.com/451510/28549595-f6419d78-708f-11e7-838c-8e049c6a2153.png)

**Probably due to CSRF**
We were able to reproduce this error by removing the CSRF field from the form when submitting. The CSRF field is a hidden field that is included with the form to help prevent attacks. It is unknown how or why this field would be removed by a user's browser, but our application _should not_ accept a form submission without this field. In other words, this is not a bug.

We do not know if the two visitors received the error for this reason, but it seems to be the most likely explanation. 

This does not seem to be a widespread problem.

**Comment by glassresistor** [comment]
Its possible the field wasn't removed but instead that the CSRF token expired(say the user left and came back much later).
A failed XSS attack would also look like this as well as a poorly behaving robot.  None imply an issue with the codebase nor is  something we should worry about unless we see a spike of them.
