### ISSUE TITLE
Implement CloudTrail

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1036]
As a developer we need a way to securely and safely(w/o breaking anything) give non-operations developers limited access to CMR's AWS infrastructure.

CloudTrail looks like a good option for Auditing IAM access.

**Comment by bengolder** [comment]
I'll just add that having CloudTrail (or something else that logs access and changes to our AWS resources and accounts) is super ✨ wonderful ✨  for security.

**Comment by bengolder** [comment]
This makes me so happy:

![screen shot 2017-08-31 at 4 05 21 pm](https://user-images.githubusercontent.com/451510/29948904-436f605a-8e66-11e7-9304-992cf0c1c76e.png)
