### ISSUE TITLE
Create Views for tables with PII

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1049]
Table that are Done
- [x] `formsubmission` 
- [x] `statusupdate`,
- [x] `visitor`
- [x] `application` 
- [x] `applicant`  
- [x] `organization`
- [x] `applicationnote`

Tables left to include:

- [x] `statusnotification`,
- [x] `county`
- [x] `tag`,

Looks confusing
- [x] `statustype`

**Comment by glassresistor** [comment]
# PII/CJIS fields to exclude in CMR

### intake - form_submission
`first_name`
`last_name`
`dob`
`ssn`
`last_four`
`drivers_license_or_id`
`case_number`
`phone_number`
`alternate_phone_number`
`email`
`aliases`
`pfn_number`
`street`
_grey area (could include PII incidentally)_
`how_did_you_hear`
`additional_information`



### intake - application_note
_grey area (could include PII incidentally)_
`body`

### intake - status_notification
`contact_info`
_grey area (could include PII incidentally)_
`base_message`
`sent_message`

### intake - status_update
_grey area (could include PII incidentally)_
`additional_information`
`other_next_step`

### intake - visitor 
`ip_address`
`user_agent`  <- can convert tihs to browser

**Comment by joduinn** [comment]
@TiffanyAndrews @bengolder @rossettistone From today's meeting, are these still the tables needed? Anything else?

**Comment by glassresistor** [comment]
@bengolder I've updated the ticket with the tables that have been done and which are now merged in develop.  I've left 
statusnotification
county
tag
statustype

for you to do so that you get practice doing them for next time.

**Comment by glassresistor** [comment]
I went ahead and updated the spreadsheet with links to the same queries in the new Clips app.  The queries seem are working fine.

One note is apparently  `grant select on all tables in purged schema to clips;` needs to be run each time we add a new view.  Apparently "grant on all" creates an individual grant on each table at that time and is itself not a type of grant. 

It should be possible to optionally do this grant if the clips user doesn't exist or if not then doing  `grant select on all tables in purged schema to public;` should grant it to all users which should work everywhere and would only cause issues if we were sharing databases with someone.

**Comment by bengolder** [comment]
@glassresistor should this be reopened, and then resolved via a new PR that includes that change?
