### ISSUE TITLE
Change Onboarding So AltTech sets up LastPass and Email

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1053]
Currently onboarding is really slow.  I'd like to change it so that:
1. Once AT sets up an email they then setup a Free Lastpass account.
2.  AT then adds the email and all other new accounts to LastPast as they go.  Making sure to use random hashed passwords(non for humans).
3.  Once they are done Infra team invites them to LastPass and they click activate in the email.

This should speed up the first day by half an hour.

**Comment by joduinn** [comment]
Tweaking summary to match reality of later verbal discussion with @glassresistor

**Comment by bengolder** [comment]
Is this in the right github repo?

**Comment by joduinn** [comment]
Found in triage

> Is this in the right github repo?

@bengolder sorry, this ticket was created in the wrong repo by accident. I'm closing this and re-creating it in the correct infra repo. Sorry for the noise.
