### ISSUE TITLE
Onboard MarkRossetti to CMR dev

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1057]
get on all necessary dev accounts
- [x] github
- [x] slack
- [x] alerts
- [x] mixpanel
- [x] newrelic
- [x] papertrail
- [x] heroku
- [x] google analytics

Pair on these
- [x] local app setup
- [x] code organization
- [x] python local debugging
- [x] deployment process
- [x] review cloud infra
- [x] production debugging

**Comment by joduinn** [comment]
Talking with @rossettistone just now, it looks like the remaining steps here are between Mark and Ben. Changing ownership to match reality.
