### ISSUE TITLE
First-pass UX feedback

### ISSUE THREAD

**Issue by rossettistone** [codeforamerica/intake#1059]
A few quick thoughts from my first time applying to clear my record :-)

First page (choose counties): Might the page feel a bit shorter and less overwhelming if the county descriptions were the full width of the center column?
Form: Description of parole could be a conditional field that only shows up if users indicate "Yes" that they are on parole.
Confirmation page: Expectations and time durations for each county felt a bit repetitive, bit of a wall of text. Could perhaps be displayed as bullets or in a table?

**Comment by TiffanyAndrews** [comment]
thanks for the feedback. Last quarter we did research and hired a consultant to do a new application form design. The information regarding that can be found here: https://drive.google.com/drive/u/0/folders/0B3BLnlbsdQ_hUmFJYXJUUW9MdFE
