### ISSUE TITLE
Audit All CMR Alerts

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1061]
List out all CMR systems and where they alerts.

Change all to clearmyrecord-alerts

Verify they work

**Comment by TiffanyAndrews** [comment]
Ben will provide Mikela a checklist of audits

**Comment by glassresistor** [comment]
Ticket #794 in the intake repo and #794 are parts of this work as well and should happen as part of this ticket.

**Comment by glassresistor** [comment]
While looking into the New Relic Audit we found an account for cmr-demo and develop as well.   For some reasons the cmr-develop New Relic account is called cmr-demo.  We tried to test if an event on cmr-develop would show up on the account it was attached to but did not see anything.

@bengolder could you quickly list here any accounts you can think of besides New Relic and Heroku that would be alerts for CMR?

**Comment by bengolder** [comment]
Aside from New Relic & Heroku, these are all critical 3rd parties that we use. I don't imagine we need alerts set up for all of them, but I wanted to list them so you can see the full extent and delve in where necessary.

- [ ] AWS RDS
- [x] AWS S3
- [x] Any alerting built on PaperTrail
- [x] CloudAMPQ Heroku add-on  <- should go through heroku
- [ ] Twilio
- [ ] Front

**Comment by glassresistor** [comment]
As far as I know AWS RDS doesn't have any alerts except maintenance windows and billing ones.   I have adding one for RDS on my roadmap. I don't know of any s3 related alerts.  

@joduinn do you know how to configure AWS to send alerts about pending maintenance and system wide downtime, etc. to?  it would be good for clearmyrecord-alerts to get them directly.

@bengolder I don't have front access so please manage that.  I also don't know about the Twilio account is it on the main CfA one?

**Comment by joduinn** [comment]
> @joduinn do you know how to configure AWS to send alerts about pending maintenance and system wide downtime, etc. to? it would be good for clearmyrecord-alerts to get them directly.

For any maintenance alert emails we get from AWS (upcoming downtimes for instances, etc), I've been coping the entire email into a new ticket, and assigning to the best-guess-owner. Per mtg with @glassresistor this feels good enough for now.

For any AWS surprise outages, like the recent s3 outage, we should forward the email to clearmyrecord-alerts@ .

**Comment by bengolder** [comment]
I just looked through Front's settings. Currently, they do not have any settings for general alerts of notifications that are sent out in response to system issues. There is a series of notifications that can be configured for each user account, which cover events such as a bounced email or text or when a new message comes in. In other words, Fronts notifications feature does not cover infrastructure issues so we may not be able to get the alerts we would like from them without writing custom code.

**Comment by bengolder** [comment]
The twilio account is the "Clear My Record" sub account on the main CfA account
