### ISSUE TITLE
Define format for Ops tickets

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1062]
Define a format for ops tickets, always create them, include change steps, pre and post-flight checks

**Comment by joduinn** [comment]
First pass done in #1074.

**Comment by glassresistor** [comment]
@joduinn i made a branch and create the file here.  since its the first file it will not let me do a PR so please review here https://github.com/codeforamerica/infra/blob/feature/first_issue_template/issue_templates/operations_changes.markdown

**Comment by joduinn** [comment]
Review in person with @glassresistor
