### ISSUE TITLE
Clips Solution User invite & instructions

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1069]
email Jenny , Sarah and Tiffany invite and user instructions to "CLIPS" tool.

**Comment by glassresistor** [comment]
I added @TiffanyAndrews on Tues and everyone else today.  To use the clips site go here
https://clearmyrecord.codeforamerica.org/clips/

At the top is a form where you can name and create queries to run.  At the bottom is a list of existing queries.   Clicking on them or creating one will run the query and present the results as a table in html.

All of the tables you have access to are named like so
what was intake_formsubmission is now purged.intake_formsubmission
