### ISSUE TITLE
Create 1 pager on Support Mode Tech-Debt

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1094]

**Comment by bengolder** [comment]
This will be defined as done once we complete:
- [x] review of the plan by engineering staff
- [x] review of the plan by the rest of the CMR team.

**Comment by bengolder** [comment]
Edits have been incorporated from the engineering team and it's ready for review by the rest of the team. https://docs.google.com/a/codeforamerica.org/document/d/1ADd5J0iQuQXVpmhlk9w6Ll3rbDl5d-mJJZD6Ts0zBAw/edit?usp=sharing
