### ISSUE TITLE
Prevent rapid duplicate submissions

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#1113]
**Alameda/EBCLC Request:** 
"People often apply  multiple times.  If they have already applied AND have been accepted as a client, is it possible for the system to intercept the subsequent applications and direct them to contact us (i.e. "Your application has already been accepted by X organization.  [For PD, the PD is working on your case and will be in touch if they need more information.] [For EBCLC, Please follow the instructions you were given after the initial application about obtaining your DOJ RAP sheet.] If you have further questions, please contact them at XXX@XXX.org ")"
 
**B Golder suggestions** 
We already have code that identifies probable duplicates (based on name and counties) and marks them in the database.
- It would only take ~1 hr max to measure the actual scale of this problem.
- The remaining work to respond to this would be to determine how we would handle those applications, and then make some logic changes. Logic changes would probably range 1-3 days of work (rough guess)

Some other work that would likely alleviate this issue:
- immediate duplicate submissions (submitted one after the other in quick succession) will likely be greatly reduced with better validation and a confirmation page where user's can check their info
- people submitting repeat apps as a response to a long wait or unresponsiveness may be reduced by allowing for more direct communication with partners.

**Comment by bengolder** [comment]
The scope of this issue has been redefined to address only those duplicate submissions that occur in rapid succession. it does _not_ address the problem of applicants submitting new applications days after a previous one.
