### ISSUE TITLE
Alameda/EBCLC Updates to Application Form

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#1115]
Alameda/EBCLC Questions to edit:
**- [ ] Revise current citizenship question to the below across all counties:** 
- Q: "What is your citizenship status?"
- [Help text] It is important for your attorney to know if you are a U.S citizen so they can find the best ways to help you. Your citizenship status will not be shared with any law enforcement agencies.
- Options: US Citizen, Legal Permanent Resident, Conditional Resident, Visa, DACA, Undocumented, Other/I don't know

Questions to add:
**- [ ] Add: Have you been denied housing or employment because of your criminal record?** 
- Options: Yes, No, I don't know

**- [ ] Add: If you have been denied housing or employment when and by which organization/agency?** 
- Open text (not required)

**- [ ] Add: Are you seeking employment that will require Live Scan fingerprinting?
- Options: Yes, No, I don't know

**- [ ] Add: Do you know if you are you registered under PC section 290 (California sex offender registration)?
- Options: Yes, No, I don't know

----

Requests from APD & EBCLC that led to the above:
- If you are not a US Citizen, what’s your current status? This will be used to ensure that the criminal record remedies filed will not interfere or harm your immigration status in any way.
a. Legal Permanent Resident, Conditional Resident, Visa, DACA, Undocumented, Other
- Have you been denied housing because of your criminal record?
a. When and what organization/agency?
3. Have you been denied employment because of your criminal record?  And will you have to go through Live Scan fingerprinting?
a. When and what organization/agency?
4. Are you registered under PC section 290 (sex offender registration)?
a. Yes or no

**Comment by sarahlizwhite** [comment]
Please let me know if the above proposal looks good and I will update the application spreadsheet @TiffanyAndrews @bengolder

**Comment by bengolder** [comment]
@sarahlizwhite @TiffanyAndrews the citizen question change brings up a dilemma about how to represent existing data. Previously the answers available were "yes" or "no". The easiest solution would be to map "yes" to "US Citizen" and "no" to "Other/I don't know". Would that be acceptable?

**Comment by bengolder** [comment]
Also, I'm assuming that the new questions are all required unless stated otherwise. Let me know if that's not correct.

**Comment by bengolder** [comment]
Are the citizenship status options mutually exclusive? Would someone ever need to pick more than one?

**Comment by TiffanyAndrews** [comment]
my suggestion:
- keep the current citizen question and just add an additional question for Alameda County only: 
Q: "What is your citizenship status?"
[Help text] It is important for your attorney to know if you are a U.S citizen so they can find the best ways to help you. Your citizenship status will not be shared with any law enforcement agencies.
Options: US Citizen, Legal Permanent Resident, Conditional Resident, Visa, DACA, Undocumented, Other/I don't know
**It might seem odd** but that way we dont have to change the question type for the original citizen question. 
@sarahlizwhite what are your thoughts?

**Comment by bengolder** [comment]
It would be easy to implement it as a separate question. If I replaced alameda's citizenship question with this one, then people would see both questions when they apply to Alameda and another county who asks about citizenship. However, even in this scenario we would have to decide how to display old applications to Alameda & EBCLC.

**Comment by sarahlizwhite** [comment]
@bengolder I don't fully understand what the challenge is. I personally think it's ok to map old data to "citizen" or "other/I don't know" but we should discuss if others disagree.

If we can, I would like revise this question across counties as this was a point of user feedback as well. The newly phrased question allows people to more clearly articulate their situation. 

And the counties that must know citizenship, they will get more granular data than (yes/no) which can only help their analysis. 

cc @TiffanyAndrews @jazmynlatimer

**Comment by TiffanyAndrews** [comment]
So based on @sarahlizwhite and user feedback lets rework the question for all counties to:
Q: "What is your citizenship status?"
[Help text] It is important for your attorney to know if you are a U.S citizen so they can find the best ways to help you. Your citizenship status will not be shared with any law enforcement agencies.
Options: US Citizen, Legal Permanent Resident, Conditional Resident, Visa, DACA, Undocumented, Other/I don't know

We will be okay around the data type change from yes/no to multiple choice. Let just document that in our data spreadsheet.

@bengolder any other flags?

**Comment by bengolder** [comment]
Okay, I'll map "yes" to "citizen" and "no" to "other/I don't know"
