### ISSUE TITLE
EBCLC Contact Page Updates

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#1122]
Remove Hayward Clinic info (below). Contact page should only list addresses for EBCLC and Oakland Clinic. (May add new Dublin Clinic address soon)

Hayward Clean Slate Walk-in Clinic
Every Tuesday, from 2pm to 4pm
24085 Amador St. 2nd Floor
Hayward, CA
94544

**Comment by lkogler** [comment]
Should we also delete the Hayward clinic for Alameda County Public Defender's Office?

**Comment by sarahlizwhite** [comment]
yes, thanks!
