### ISSUE TITLE
As CfA staff, I don’t want emails or text messages to bounce

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1140]
Integrate 3rd party validation
- [x] Integration tests (1D)
- [x] Write a backend validator that calls a third party service (0D)
- [ ] Write an asynchronous validation function in Javascript and add it to email & phone fields (2D)
- [ ] Add a minimal loading indicator for validation on phone & email fields (.25D)
- [ ] Add a minimal javascript function for rendering errors and email suggestions (.25D)

**Comment by TiffanyAndrews** [comment]
@bengolder Can you add this to PR #1183?

**Comment by bengolder** [comment]
Done. (also unchecked some checked boxes to more accurately reflect what has been completed).

**Comment by bengolder** [comment]
We decided to implement this entirely as a backend validator in order to simplify the user experience and deliver the core feature faster.
