### ISSUE TITLE
Add custom storage backend to store static files in its own bucket(https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L186)

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1174]

**Comment by glassresistor** [comment]
Currently the both are setup but both are using the static file bucket.

- Needs to create custom storage for media which uses a new bucket.
- Compress doesn't play nice with staticfiles and s3 and requires a local copy of the files to work.
