### ISSUE TITLE
Write request and response handling functions for Twilio’s lookup service

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1178]

**Comment by bengolder** [comment]
@TiffanyAndrews We're not sure if this is going to provide much additional value over the phone number format validation we introduced about 3 weeks ago: https://github.com/codeforamerica/intake/issues/1103

Twilio does allow us to tell if a phone is a landline or not, but does not directly answer the question of whether or not it is SMS capable. Jen & Ben previously thought that it did give us that information, but while attempting integration we realized that it did not.

Suggestion: We could look at the data for bounced numbers to see how much the existing validation helped, and check if SMS to landlines is a significant contributor to our bounced phone numbers. Not sure if this is high enough priority to work on right now.

Sincerely,
_Laura & Ben_

**Comment by bengolder** [comment]
I just noticed that Twilio uses the same open source phone number validation code that we apparently added in the phone number fixes 3 weeks ago. So in terms of validating the format of the phone number, we are currently using the same core library as Twilio does.

**Comment by bengolder** [comment]
Per a conversation with Emma, we are not including Twilio's API because it does not give us much additional functionality. Closing this ticket.
