### ISSUE TITLE
Update display form for APD and EBCLC

### ISSUE THREAD

**Issue by maxmcd** [codeforamerica/intake#118]

**Comment by bengolder** [comment]
The display form does a poor job of handling missing fields.
Fields need to be organized in a way that looks okay for any of the users.
Apostrophes and other html escaped entities are escaped too many times.
- [x] handle missing fields
- [x] organize all fields nicely
- [x] don’t double escape the text #120

**Comment by bengolder** [comment]
![look at alameda app detail-001__entered login info](https://cloud.githubusercontent.com/assets/451510/18413436/dc9cc410-775c-11e6-801a-04b33c092877.png)
