### ISSUE TITLE
Update Communication Spike Document

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1186]
https://docs.google.com/document/d/1Fz2scDYuPHZT1Nfd69ifQVX2UzfTQ34e0ReLaVBKa-4/edit

**Comment by lkogler** [comment]
Ben and I had a conversation about this, and came up with two possibilities:

1. The existing documented plan looks not quite complete -- there are some unresolved design issues that could produce an unknown amount of additional work.

2. We thought of an alternate idea that would exclude in-app history and free-form messaging, and would instead just proxy messages to and from the org user's email. We believe this would be substantially less work (perhaps 1/3, but we haven't done a detailed breakdown).

Would you like us to create a more detailed proposal for the second option? Or is in-app message history a non-negotiable requirement?

**Comment by bengolder** [comment]
This will done once the plan is reviewed by Sarah and Jazmyn, edited, then delivered to PM

**Comment by bengolder** [comment]
Added a proposal for the second option (Email relay without history or significant tracking)
https://docs.google.com/a/codeforamerica.org/document/d/1L0CPdl2oY8XZK4tmWL74fJ4UWVE5cmleKliJIV7GSnE/edit?usp=sharing, which was reviewed by Sarah and Jazmyn
