### ISSUE TITLE
Implement new Status Types

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1195]
this is done when we have the next iteration of status types implemented and deployed

**Comment by jazmynlatimer** [comment]
We've reached agreement on the set of status types to implement. Content is written and ready for devs to implement. 
https://docs.google.com/spreadsheets/d/1sBVb_vD0wnN2_N47MM-LebvkROh_qlAZYjWqV61Wai8/edit#gid=0

**Comment by jazmynlatimer** [comment]
UAT notes:
- please reorder the status types in the create status update page to be in this order:
In Review,
No Convictions Found,
Eligible,
Court Date Scheduled,
Cant Proceed: probation,
Can't Proceed: fines/fees,
Can't Proceed: need more info,
Can't Proceed: no eligible convictions,
Can't Proceed: other,
Outcome: Granted,
Outcome: Denied
- everything else looks perfect!
