### ISSUE TITLE
Allow Application Editing [2D] --> [4D]

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1213]
As an org user, I want to make corrections to the information on applications that pertain to my org, so I can ensure that notifications go to the correct contact information.

- Add ApplicationEdit page, with correct access control
- Create ApplicationEditForm and logic to combine it with county form.

Fields: 
- contact pref
- name
- alias (not shared)
- phone
- alt phone (not shared)
- mailing address (not shared)
- DL (not shared)
- email
- dob (not shared)
- ssn (not shared)
- case number (not shared)

**Comment by bengolder** [comment]
Link to mocks: https://app.mural.ly/t/clearmyrecord1239/m/clearmyrecord1239/1497305573769/f8ba5a3b37b3cb87d938f75dbf613974fac98cb5

**Comment by bengolder** [comment]
Current screenshot. @jazmynlatimer does this look okay?

![Screen Shot 2017-10-05 at 4.34.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54c94d54a0404e0300302115/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454f66b7191a37cf1112f4f5c575ecc3c4a4356bcbbd671f3e57862804e0eead63b5e76cf6b45ffb18417be02b8208b1987e2bf824dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df64ce34953a01a3f62e7762431.png)

**Comment by bengolder** [comment]
In trying to complete the changes to allow edits, we've encountered unexpected difficulty with handling certain edge cases.

Assumptions leading into the "Existing Bad Data Dilemma":

- some applications contain bad data
- we have changed our validation to better catch and filter out such bad data
- we want people to be able to edit data
- they might want to edit an application with bad data
- if they do, they might not want to edit the bad data itself
- if they edit an application with bad data, but don't edit the bad data, we don't want to prevent them from inputting new good data in a different field

Task that's giving me trouble:
- we need to make a form and logic that allows a user to see and edit bad data, but will not stop them frmo making changes if they don't edit the bad data.

There are only 4 fields that might have bad data:
- date of birth
- phone number
- alternate phone number
- email

Approaches:
1. a form that displays bad data if it exists and carefully filters out errors for unchanged existing bad data
    - Requires logic changes to the data handling pipeline at multiple stages to accommodate data. Each of these needs some way to detect whether an exception should be made.
        - rendering the form
        - showing display values (mostly done already)
        - validation
        - view routing based on form validation
        - saving the model
2. Move invalid existing data into new column, show it to the user but don't let them edit it.
    - add a new 'old_invalid' column for each of the fields that may contain bad data
    - migrate the data using a script and form. Only store invalid data in the old column.
    - This would require most of the exceptions listed above, but would simplify their logic by persisting an additional value that can be checked throughout the process.
3. When someone opens an application with existing bad data, then the bad data is lost if they save their changes to any other fields.
    - this would be the easiest to implement.
    - It is destructive.
    - This will only affect a small fraction of cases

The origin of this is the escalation of validating data _and_ allowing people to edit that data _and_ wanting to keep the old bad data

These edge cases only affect a fraction of all applications. The case is the combination of all of these factors:
- application already has bad data (~2% of apps)
- a user wants to edit that application (subset of 2%)
- the user does not want to edit all the bad data in the form. (subset of subset of 2%)

**Comment by bengolder** [comment]
After discussion with @TiffanyAndrews @jazmynlatimer & Pam, we've decided to switch from approach 1 to approach 3, while ensuring that we display validation errors for existing data to the user and send alerts.

**Comment by sarahlizwhite** [comment]
Adding comment based on conversation I had with @bengolder. Ability to edit DOB, DL, SS could become problematic if our partners aren't careful or inadvertently edit/remove this data. 

Something to keep an eye out for as this feature is used. 

We may want to add more barriers to editing those pieces of info like a "are you sure, you want to make this edit?" or not allow those fields to be edited. 

cc @TiffanyAndrews @jazmynlatimer
