### ISSUE TITLE
Add notification emails for Application Edits [1D]

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1214]
As an org user, if someone else updates the information on an application I am handling, I want to be notified so that I can keep my records up to date. (1D)
Create application edited notification template
Add notification function
Call notification when saving edits to a Form
Q: is sending on save an appropriate trigger?

**Comment by bengolder** [comment]
Question about notifications for org users:
Let's say a user at Fresno edits an application that is shared with San Diego and Santa Clara.
Who, exactly, should we send notifications to?

Here are some of our options:
1. send it to every user at all three organizations (Fresno, San Diego, & Santa Clara)
2. send it to any user at each organization who is currently receiving the daily "new applications" email. 
3. send it to the listed public email for each org (not all orgs have an email)

Laura & I recommend 2, it seems the most intuitive. 3 is tricky becuase some won't have an org email and because that email is usually more public facing.
@TiffanyAndrews @sarahlizwhite @jazmynlatimer

**Comment by bengolder** [comment]
![screen shot 2017-10-12 at 11 52 50 am](https://user-images.githubusercontent.com/451510/31513683-e96af9e4-af43-11e7-98d8-03cb2306bd6e.png)
I believe we've changed this to just list the changes instead just list the old and new values.

When we list the values, it would look something like this:

- Phone number
    - Before: ""
    - After: "(555) 555-5555"

**Comment by jazmynlatimer** [comment]
I'd do number 2, since that user will be checking their email for CMR notifications regularly and because the person who process incoming applications is usually the same person that does smaller tasks like update contact information.
