### ISSUE TITLE
Data Request: Applicants info.from Fresno, Sonoma, Solano and Contra Costa

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1219]
Requirements:
- All applications 
- counties: Fresno, Contra Costa, Solano, Sonoma
- submitted: 8/1/2017 -9/30/2017 
FIELDS
- full name
- phone
- email
- org.name
- app. id

**Comment by lkogler** [comment]
Script for data export: https://gist.github.com/lkogler/2fbc820935c344049be5f6acfe97c7fa

**Comment by bengolder** [comment]
We sent an email with a link to the data.
