### ISSUE TITLE
As an applicant, if someone edits my application, I want to be notified so I can ensure the edits are correct and changes I would consent to.

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/intake#1224]
- We should send this to both the old and new contact info, if email or phone was edited.
- We should include information about who made the change and who to contact if there is an error.

Concerns/Questions:
- if we send it to the "old" contact info, but the old info is known to be incorrect (someone who never applied).
- do we message it differently for old & new contact info?
- do we include the old and new values in the message? in messages to both old and new?
- if we allow edit on dob or ssn do we also send the changes to these values?
- what information do we send to each contact about who made the changes?

**Comment by TiffanyAndrews** [comment]
@bengolder @lkogler Jazmyn and I brainstormed a solution that is outlined via the comment in the murally document.

**Comment by TiffanyAndrews** [comment]
email context: Hello,

An application with your contact information has been updated, The  change was made by {org.name}.
Here is the information that was changed:
- {list changed field }
 We value your privacy. If you did not approve this change or would like more information please contact {org email}.
