### ISSUE TITLE
As an org user, if a client replies to my status email, I want to receive that reply in my regular email inbox.

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#1233]
During user profile creation, add a routing action to mailgun using mailgun’s API http://mailgun-documentation.readthedocs.io/en/latest/api-routes.html#actions (.5 Day)
Write a management command to fill out the email routing for existing users (0.5 Days)

**Comment by bengolder** [comment]
What this means: Any emails to `{username}.{org_slug}@clearmyrecord.org` will be routed to the user's login email address.
