### ISSUE TITLE
Switch all emails to be sent through mailgun

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/intake#1256]
Django error alert emails should still work on Lambda. If not, switch all emailing to Mailgun

**Comment by glassresistor** [comment]
Both should work but its best to use mailgun so if its easy I think we should switch.  It might be easier than making sure Lambda isn't going to be marked as spam.

**Comment by glassresistor** [comment]
Yeah setting up mailgun is trivial.  Install this package and add these settings

https://github.com/bradwhittington/django-mailgun

```python
EMAIL_BACKEND = 'django_mailgun.MailgunBackend'
MAILGUN_ACCESS_KEY = 'ACCESS-KEY'
MAILGUN_SERVER_NAME = 'SERVER-NAME'
```

**Comment by glassresistor** [comment]
Looks like django-mailgun is deprcated for https://github.com/anymail/django-anymail

After looking at our application we are using sendgrid to send emails  and it has the same configuration as CI which means that in theory travis will send emails.

For now I'm going to leave it on sendgrid.
