### ISSUE TITLE
Alerts for too many login attempts

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/intake#1259]

**Comment by bengolder** [comment]
Send as an email, if possible, show the account being attempted.

**Comment by bengolder** [comment]
looks like django-allauth already provides a hook for limiting logins. We could supplement this code with an alert: https://github.com/pennersr/django-allauth/commit/ae472772c8f93bcb972205c9d7159051cf6f413a#diff-91ece39d6737e76fd671928867a3911cR394

Settings:
- `LOGIN_ATTEMPTS_TIMEOUT`
- `LOGIN_ATTEMPTS_LIMIT`

**Comment by bengolder** [comment]
Laura says: if we limit the number of failed login attempts in a time period, do we really need an alert too? I think no.

**Comment by bengolder** [comment]
I would propose we set a high limit. How about 20 failed attempts?
