### ISSUE TITLE
Case # should be county specific or shouldn't be editable

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#1266]
Ex: As a public defender in Alameda, if an applicant doesn't provide a case number (or provides the wrong one) and I change it - an org also accessing that application may think that case number applies to their county/org. 

Without delineating case numbers per county/org - counties and orgs will be editing and replacing each other case numbers without realizing it.

**Comment by bengolder** [comment]
One immediate idea for a way to resolve this would be to make every case number question county-specific, for example Alameda County Case Number, and Santa Barbara County Case Number. We could then migrate the old data into one or more of them depending on the counties applied to.

**Comment by bengolder** [comment]
The easiest thing to do would probably be to remove it from the list of editable fields.

**Comment by bengolder** [comment]
I'm going to put up a PR that removes case number from editable fields
