### ISSUE TITLE
Make it easier to answer questions about users

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#127]
Make a script that can pull counts for unique answers from form submissions quickly.
Integrate it into stats page.
- [x] where did they come from?
- [x] How many people start but don't finish?
- [x] What kinds of errors are they running into on the form?
- [x] How far do they get?
- [x] how long does it take people to finish?

**Comment by jazmynlatimer** [comment]
Would love to have these metrics:
- [x] city of mailing address
- [x] birth year
- [x] preferred contact method
- [x] is on parole/probation/charged/serving sentence
- [x] employed
- [x] monthly income
- [x] how they heard
- [ ] time of day they applied
- [ ] day of week applied
- [ ] time of day opened by PD
- [ ] day of week opened by PD
- [x] avg apps per day/week/month

Cross correlations would be useful. particularly between counties.
