### ISSUE TITLE
Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1275]
We are currently getting an error message in our production logs that a  memory quota has been exceeded.

**Comment by bengolder** [comment]
```
Oct 30 10:42:22 cmr-prod heroku/web.2:  Process running mem=519M(100.5%) 
Oct 30 10:42:22 cmr-prod heroku/web.2:  Error R14 (Memory quota exceeded) 
```

**Comment by bengolder** [comment]
This error message appears in the logs every 30 seconds backwards in time from now to Oct 29th around 8:50pm

The message appears repeatedly on other days in the past (but not in between these days):
- October 25th
- October 20th
- October 17th

**Comment by bengolder** [comment]
From [Heroku's Docs](https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded):
> If this error occurs, the dyno will page to swap space to continue running, which may cause degraded process performance
> If you are getting a large number of R14 errors, your application performance is likely severely degraded. Resolving R14 memory errors are language specific

**Comment by bengolder** [comment]
This does not seem to be significantly affecting response times
![screen shot 2017-10-30 at 10 53 36 am](https://user-images.githubusercontent.com/451510/32186895-9cdde39a-bd60-11e7-9495-a191549cc9ed.png)

**Comment by bengolder** [comment]
![screen shot 2017-10-30 at 10 55 02 am](https://user-images.githubusercontent.com/451510/32186975-d14c111a-bd60-11e7-861d-9a6b83965b63.png)

**Comment by glassresistor** [comment]
Taking a look at the archived logs which go back further than 2 weeks I check back to Oct 11th and didn't see R14 in the logs until Oct 17 so we should be looking at what code changes happened that day.

**Comment by bengolder** [comment]
One possible cause: compiling large prebuilt PDFs when SF has not logged in for a while.

**Comment by bengolder** [comment]
Able to reproduce by searching followups with one letter:
```
Oct 30 12:04:20 cmr-prod heroku/router:  at=info method=POST path="/followups-autocomplete/" host=clearmyrecord.codeforamerica.org request_id=2c568497-9e7c-4673-a64f-f6cebf125300 fwd="69.12.169.82" dyno=web.2 connect=1ms service=7682ms status=200 bytes=2499003 protocol=https 
Oct 30 12:04:28 cmr-prod heroku/web.2:  Process running mem=537M(104.7%) 
Oct 30 12:04:28 cmr-prod heroku/web.2:  Error R14 (Memory quota exceeded) 
Oct 30 12:04:50 cmr-prod heroku/web.2: Process running mem=537M(104.7%) 
Oct 30 12:04:50 cmr-prod heroku/web.2: Error R14 (Memory quota exceeded) 
Oct 30 12:05:12 cmr-prod heroku/web.2: Process running mem=537M(104.7%) 
Oct 30 12:05:12 cmr-prod heroku/web.2: Error R14 (Memory quota exceeded) 
```

Connecting it with https://github.com/codeforamerica/intake/issues/885

**Comment by bengolder** [comment]
Earlier errors on Oct 20th & 17th happened on worker processes (rather than web) and the memory overload was preceded by submission of an application to San Francisco. Below, you can see slack trying to expand the link to an application to SF, as app links are posted in slack after new submissions.
```
Oct 20 13:02:51 cmr-prod app/worker.1:  [2017-10-20 20:02:51,007: INFO/PoolWorker-7] 2017-10-20 20:02:51.007729	call_to_mixpanel	distinct_id=b74b496bdac84b6dbf34667c2dbd7507	properties={'browser_family': 'Slackbot-LinkExpanding', 'is_tablet': False, 'is_pc': False, 'full_path': '/accounts/login/?next=/application/4770/', 'visitor_referrer': '', 'device_family': 'Spider', 'device_model': 'Desktop', 'is_mobile': False, 'path': '/accounts/login/', 'language': 'English', 'is_bot': True, 'locale': 'en', 'os_version': '', 'visitor_source': '', 'compact_user_agent': 'Spider / Other / Slackbot-LinkExpanding 1.0', 'browser_version': '1.0', 'os_family': 'Other', 'is_touch_capable': False, 'device_brand': 'Spider'}	event_name=site_entered 
Oct 20 13:02:51 cmr-prod app/worker.1:  [2017-10-20 20:02:51,010: INFO/PoolWorker-7] Task project.services.mixpanel_service.log_to_mixpanel[378b136a-098b-4579-9dce-8c451da2c37a] succeeded in 0.022109832003479823s: None 
Oct 20 13:02:51 cmr-prod app/worker.1:  [2017-10-20 20:02:51,415: INFO/PoolWorker-2] Task intake.tasks.celery_request[722d55e3-5fdb-49a9-aacc-c196a1138d96] succeeded in 0.8427393549936824s: None 
Oct 20 13:02:55 cmr-prod app/worker.1:  [2017-10-20 20:02:55,410: INFO/PoolWorker-3] Task intake.tasks.add_application_pdfs[15aa5ff2-cc5c-4a7f-8a47-ef1870e1e9ca] succeeded in 4.902122600993607s: None 
Oct 20 13:03:08 cmr-prod heroku/worker.1:  Process running mem=543M(100.6%) 
Oct 20 13:03:08 cmr-prod heroku/worker.1:  Error R14 (Memory quota exceeded) 
```

**Comment by bengolder** [comment]
In summary, we have _two_ likely causes of this error:

1. Autocomplete search results of enormous queries, triggered when cfa staff types in names into the search box and queries are triggered on single letter searches. (Created issue #1281)
2. If San Francisco does not login for long enough, their prebuilt PDF will be built up in memory with new applications, and may become big enough to exceed our memory quota during the construction of this concatenated PDF. (Created issue #1280 )
