### ISSUE TITLE
Fix mixpanel integration

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/intake#1296]
Mixpanel data stopped being recorded sometime around noon on 10/31.

**Comment by lkogler** [comment]
- [x] Fix environment variable boolean parsing in prod
- [x] scrape production logs to see what things we missed sending and assess damage
- [x] make a script to send out important missed Front notifications
- [x] Manually send out missed mailgun notifications
- [x] Check for additional missed notifications from 11/6 that weren't in the initial log bundle
- [x] postmortem scheduled and timeline written[Mikela eidted]

**Comment by lkogler** [comment]
Status of this issue:
- There were 160 Front notifications that failed to send. We created a script to pull the info out of the logs and sent the (delayed) notifications yesterday afternoon.
- There were only 4 missed Mailgun notifications, all related to a single event, in which Annie updated an applicant's mailing address and DOB. It is more difficult to create a script to automatically send the Mailgun messages, so we propose manually sending them out via Front (since there are only 4 messages).

@TiffanyAndrews Does this sound OK to you? If so, can you pair with me on sending the Front emails?

**Comment by glassresistor** [comment]
The reason the mailgun messages still went out is because they are not affected by DIVERT_REMOTE_CONNECTIONS.  See  #1305

**Comment by TiffanyAndrews** [comment]
@lkogler The plan outlined above sounds good. I am available this afternoon or tomorrow morning to pair on sending out the 4 messages via Front.

**Comment by glassresistor** [comment]
Everything has been fixed and a postmortem has been scheduled.  Any tasks that come out can have there own tickets.
