### ISSUE TITLE
Add more metrics to the stats page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#176]
- fix completion times to account for users who submit different apps over time from the same computer
- add more context so the measurements are easier to understand (for example, the time interval used for each)
- Break down drop off rates by county and by individual pages.
- Most common validation errors
- Channel quality for "source" parameters (from use of our shareable button)

**Comment by jennifermarie** [comment]
We have these. Let's display them.

**Comment by jennifermarie** [comment]
Re: first item -- "fix" may be a stretch for this ticket, but let's aim to log things where appropriate.

**Comment by bengolder** [comment]
This issue is outdated and should be recreated if needed. Closing.
