### ISSUE TITLE
Combine case details pdf with SF pdf

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#196]
case details and the pdfs we send to SF are totally separate. we should combine the two so that SF can see more of the details.

The tools that may be used are:
* [PyPDF2](https://pythonhosted.org/PyPDF2/)
* [pdfrw](https://github.com/pmaupin/pdfrw)
* our existing pdf tool (which is slower)
--SFPD--

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer @bengolder Is this item done? If not, it is still a request or need from SF?

**Comment by bengolder** [comment]
not done, and is still a need.
