### ISSUE TITLE
Write out status tag content

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#216]
Write out 
- Status Groups
- Status Tags
    - labels
    - templates
        - context
            - globals (name, org, county)
            - inputs (court date)

**Comment by jazmynlatimer** [comment]
https://docs.google.com/spreadsheets/d/1HtP7JqLdzvCYHXy5ZYys9bU7dxeMZg-x9RbhC4WpH3Q/edit#gid=1839841572
