### ISSUE TITLE
Check if they would use paper or voice notifications

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#217]
We could produce a printabel notification letter and this could be attached to emails even
in any case, would the orgs want to send this type of notification?

this has implications for our preferred contact question

**Comment by jazmynlatimer** [comment]
APD says they can't commit to calling and mailing people.

**Comment by jazmynlatimer** [comment]
Ideas for how to handle all cases:

If they prefer voicemail:
![screen shot 2016-12-09 at 1 40 03 pm](https://cloud.githubusercontent.com/assets/5255453/21065589/fe3e2154-be15-11e6-989f-19e03461f393.png)

If they prefer snail mail:
![screen shot 2016-12-09 at 1 43 57 pm](https://cloud.githubusercontent.com/assets/5255453/21065595/066c24b6-be16-11e6-83d4-06be9c6b4e79.png)

If they prefer sms or email:
![screen shot 2016-12-09 at 1 44 48 pm](https://cloud.githubusercontent.com/assets/5255453/21065600/0f2cb214-be16-11e6-976a-202650c3f4be.png)

**Comment by tmaybe** [comment]
It's still possible for people to get charged to receive sms, so we might encourage shorter messages for that medium. I think a message as long as the one shown in the mockup would get broken into multiple parts.
