### ISSUE TITLE
Address the conflation between Applicant, FormSubmission, and an individual person

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#236]
Currently Applicant is based on a common session identity, while FormSubmission is based on a particular POST with certain data.

Neither of these quite map to individual people.
FormSubmission includes a significant number of duplicate submissions.
Applicant includes some computers that were used to submit applications for multiple people (for example, two people in the same household)

It's easier to merge duplicates than split applicants, I think.

**Comment by jennifermarie** [comment]
Update: Application model is now explicit; once we define a path for applicant-user accounts, Applicant will also be clear.
