### ISSUE TITLE
When Alameda partner transfers an application, applicant should be notified

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#238]
Right now an applicant doesn't know if APD transfers a case to EBCLC or vice versa. They should be notified when this happens to prevent confusion.

**Comment by jennifermarie** [comment]
Do we have preferred copy for the message on this? @jazmynlatimer @bengolder

**Comment by jazmynlatimer** [comment]
If transferred from APD to EBCLC -
"Your Clear My Record application is now being handled by East Bay Community Law Center. Your next step is to get your state RAP sheet. Please follow the instructions here: link"

[2:22]  
If transferred from EBCLC to APD -

[2:23]  
"Your Clear My Record application is now being handled by Alameda County Public Defender's Office. (APD's next step)"

**Comment by bengolder** [comment]
@jazmynlatimer Could you give me feedback on this as a final message?

I edited your examples only because I thought it might be ambiguous if someone submitted a multi-county app. I followed the SN template.

```
Clear My Record Update from {author_name} at {from_organization}:

Your {county_name} County application is now being handled by
{to_organization}. {to_org_next_step}
```
