### ISSUE TITLE
Reviewing your declaration letter deletes everything you've written so you have to write the whole letter again :(

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#281]

**Comment by jazmynlatimer** [comment]
When a user is on declaration letter preview, and decides they want to edit it, so they select the "Edit" button, it goes back to the declaration letter form but it is empty so they have to write the whole thing over again. When a user goes to edit what they've wrote, it should still be there.

**Comment by bengolder** [comment]
closed with https://github.com/codeforamerica/intake/pull/283
