### ISSUE TITLE
Update consent question for all counties

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#286]
Add consent note as an explicit field

![screen shot 2017-01-20 at 3 05 50 pm](https://cloud.githubusercontent.com/assets/451510/22169814/13a41ad0-df2c-11e6-80a0-9a3c6a2646d0.png)

**Comment by jazmynlatimer** [comment]
If they select No on any of these questions, throw a form validation warning:


Which one is more clear?

- An attorney will not accept your application unless you select "Yes" as your answer to this question.
- An attorney will not accept your application if you select "No" as your answer to this question. 
- You must agree to the terms of this question (select "yes") for an attorney to accept your application.

**Comment by jazmynlatimer** [comment]
Decision: Add these fields for consent - 

- [ ] I give permission for attorneys in the counties I am applying in to: 
1) Review my criminal record 
2) File a petition with the court, if I qualify 
3) Attend a court hearing on my behalf

- [ ] I understand that: 
1) Submitting this application does not guarantee that I will qualify for services 
2) It could take a few months to complete the process of clearing my record


If they do not select the checkbox, throw an error message that says:
You must agree to this statement for an attorney to accept your application.
