### ISSUE TITLE
remove LIVE_COUNTY_CHOICES & streamline constants

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#304]
- [ ] Use a queryset with the county choice field
- [ ] display all county names based on universal public view context (oxford comma if <= 3, throughout California if >3)

**Comment by bengolder** [comment]
For this to work, the county question needs to be able to use a `QuerySet` for it's `choices` attribute.
Perhaps a good solution to this is to allow `choices` to be a function that returns a choices tuple or list.
Alternatively, a `ModelChoiceField` & `ModelMultipleChoiceField` would be less general

I may be able to override the choices property on the field class with a dynamic attribute

**Comment by rossettistone** [comment]
@bengolder Without digging on the code for a bit, I'm not 100% sure I understand this whole issue, but it sounds like something our refactor of `constants.py` in the CNL release might have at least partially addressed. Can you comment?

**Comment by bengolder** [comment]
@rossettistone yeah, we handled this recently. this is closeable.
