### ISSUE TITLE
Check that transfer logic is okay

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#309]
Situation: Org A sends a status notification. Org A then transfers the application to Org B (example: status update is "can't proceed" because income information is missing, once applicant provides that information, Org A realizes they need to be handled by Org B and does the transfer). 

Question: what happens to the status updates and how should they look to Org B after transfer?

**Comment by jennifermarie** [comment]
Temporary answer: Org B will see status updates from Org A in the app history for the application. These will need to be included in the transfer before delete.

**Comment by bengolder** [comment]
@jennifermarie I believe this is currently implemented in the manner described by the temporary answer. Is that the case?
