### ISSUE TITLE
Style status update forms and bring in help text

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#311]
Write a custom template so the checkboxselect and radioselect inputs in the Status Update form match the mocks / FormSubmission form.

**Comment by bengolder** [comment]
![screen shot 2017-02-07 at 12 23 00 pm](https://cloud.githubusercontent.com/assets/451510/22709914/586e6208-ed30-11e6-9dbe-0e1783fda88e.png)
![screen shot 2017-02-07 at 12 22 54 pm](https://cloud.githubusercontent.com/assets/451510/22709915/58824552-ed30-11e6-8800-824077ee2340.png)
