### ISSUE TITLE
Write additional tests for Status Update / Notification feature

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#322]
Split-out from #219 because some tests were living on a different branch.

This ticket includes tests for:

- User can review Status Notification Message
- User can edit the message body of a Status Notification
- User cannot edit the "intro" line of a Status Notification message
- User can send a Status Notification
- User sees a success flash after creating a Status Notification
- Latest status is reflected in the App Index

**Comment by bengolder** [comment]
The ^ above commit (1e59ce9) adds some test methods and classes to cover this and other needed tests
