### ISSUE TITLE
Permission testing for cross-org applications

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#335]

**Comment by bengolder** [comment]
Specifically: For multi-org submissions, make sure that any given org user only sees the latest status and status history for their own org, not for other orgs.

**Comment by bengolder** [comment]
This was apparently well-structured in the code and the test was redundant. But our mock data was connecting users from one org to status updates from other orgs, causing some alarm when viewing demo data. In other words, incorrect relationships in the mock data were the cause for concern
