### ISSUE TITLE
Add another consent checkbox (3 total)

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#340]
Partners want another consent checkbox for getting a client's understanding that submitting this form does not constitute attorney-client relationship.

(exact wording coming soon)

**Comment by sarahlizwhite** [comment]
This doesn't have to be a third consent box - could be built into existing. They didn't have a preference.

**Comment by jazmynlatimer** [comment]
Edit wording of the 1st consent checkbox to -  

"Do you understand that not everyone qualifies for help, submitting this form does not guarantee that you will be officially represented by an attorney, and it might take a few months to finish?"   

"Yes, I understand"

**Comment by bengolder** [comment]
![screen shot 2017-02-13 at 7 27 19 pm](https://cloud.githubusercontent.com/assets/451510/22913925/a5bc5ea6-f222-11e6-9907-0384f3e0e06f.png)
