### ISSUE TITLE
Send partners email to set up their CMR usernames and passwords

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#347]
Jaz will slack email addresses

**Comment by sarahlizwhite** [comment]
These are the logins for Santa Cruz. Please send invites to set up accounts but don't add Santa Cruz to live site until I signal. :)

Cassandra Licker: clicker@scdefenders.com
Clara Steitz: csteitz@scdefenders.com
Jim McMillin: jmcmillin@scdefenders.com
