### ISSUE TITLE
Add e-signature functionality to Santa Clara County application

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#351]
SCC judge specifically requires their official consent form to the signed by applicants.

**Comment by sarahlizwhite** [comment]
Link to meeting notes where e-signature comes up. https://docs.google.com/document/d/1zg_eYT8RkMQPJD8_e4Zzxtonq9mXS1ibtgfyUluBbUo/edit

**Comment by jazmynlatimer** [comment]
Rough idea is that - to submit the CMR application, an applicant would provide their e-signature. The e-signature would then be added to SCC's official consent form PDF. When an attorney goes to download and print an applicant's application, the e-signed consent form would print along with the rest of the CMR application (similar to SF's rap request PDF).

**Comment by jazmynlatimer** [comment]
Next step - @sarahlizwhite is meeting with SCCPD about privacy/security and will get more clarity from them about:

- do they need the consent form to be signed before they can check an applicant's eligibility? If only eligible applicants need to sign the consent form, we might suggest launching CMR without adding any e-signature functionality.
- would they be okay with launching CMR without the e-signature/consent form functionality? Would speed things up and might be able to come back to this issue later if other counties have the same barriers.

**Comment by bengolder** [comment]
Do we have a copy of the official SCC consent form required for applicants?

**Comment by sarahlizwhite** [comment]
Not a priority right now but may come up again.

**Comment by bengolder** [comment]
Thanks @sarahlizwhite closing until it comes up again.
