### ISSUE TITLE
Send partners email so they can set up their usernames and passwords

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#359]
ON HOLD until they have gotten the go ahead from their supervisors and we have addressed the consent form issue

**Comment by sarahlizwhite** [comment]
Pending list of e-mails

**Comment by sarahlizwhite** [comment]
e-mail to use: expungement@pdo.sccgov.org

**Comment by sarahlizwhite** [comment]
Please also make one for Sarah Wheatley sarah.wheatley@pdo.sccgov.org
