### ISSUE TITLE
Make working prototype for CCC intake

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#38]
This is a significantly larger task than first glance. This would transition the app to be multi-county from single county.
- [x] refactor form for easier integration (#56, #48, #47)
- [x] add an acceptance test for getting through the form for CC
- [x] create County class with default data, slug and nice name
- [x] create initial data that links the correct orgs to the correct counties
- [x] make a custom initial data loader so that we can load translated data
- [x] create a form with fields common to CCC and SF
- [x] create a form specific to CCC
- [x] add county question and county selection form
- [x] create a view for selecting the county
- [x] create a way to combine forms, or create a combined county form (SF + CC)
- [x] create a way to delegate to the correct form based on the input county
- [x] record which county a submission was intended for
- [x] create migration to populate counties and link existing submissions to san francisco
- [x] ensure that a view can pull out county information and add it to the submission
- [x] deal with case where someone goes back and adjusts the county
- [x] create a clearer sketch of the form flow
- [x] make sure that bundles are county specific
- [x] make sure that pdfs are organization specific
- [x] remove "other" as a county option
- [x] add organization as a column on relevant app logs
- [x] add a migration to set san francisco as the organization on relevant existing app logs
- [x] submission detail template
- [x] submission detail view (distinct from pdf)
- [x] make submission detail the default view of a specific submission
- [x] For each org, let the bundle page be a pdf or a bunch of app details
- [x] make sure that app_index only shows apps for that org
- [x] edit stats to tell us the application counts for each county
- [x] edit notifications to tell us which county was applied to
- [x] edit user-facing text to reflect multi-county
  - [x] Splash page
  - [x] context while filling out form
  - [x] thanks page
  - [x] confirmation emails & texts
- [x] improve display of app detail

Field reference: https://docs.google.com/spreadsheets/d/1RwXX_ZXIq7jqXfllP2QBwXNfvpPAscOOylSl52gOfFk/edit#gid=70218205
- mostly removing fields
- add "where does your income come from?"

Email, unknown.
No PDFs needed.
Form data should be in email.

**Comment by jazmynlatimer** [comment]
CCC email: cleanslate@pd.cccounty.us

**Comment by jazmynlatimer** [comment]
copy updates for multicounty - https://docs.google.com/document/d/1TMkIrSpnJBZUYeMFxiNAMs_L9yB7IQWjemqq5spG0ic/edit#
