### ISSUE TITLE
Change articulate of # of cases prompt for status update checker

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#436]
Jenny and I were reviewing demo slide deck in prep for San Diego and realized the box for "# of cases" for status notifications is confusing. 

What do you think about changing to: 

"# of petitions being prepared" or 
"# convictions under review"

Basically, the logic is there could be multiple petitions and multiple convictions but likely only 1 case. Or if anything a case could include (or leave out) various convictions.

**Comment by bengolder** [comment]
That box doesn't exist in the deployed version.

**Comment by sarahlizwhite** [comment]
Ok good to know. But will be for Santa Clara, right?
