### ISSUE TITLE
Make Faker comply with reality

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#446]
Currently, Faker is behaving as-expected and generating realistic emails/phone numbers that do not belong to real users. However, Front cannot tell the difference, and it is possible that mock applicants have phone numbers / email addresses owned by real humans.

We can fix this by enforcing restrictions on Faker, such that mock applicants get some form of `bgolder+test_applicant@codeforamerica.org`as their email address, and a friendly phone number as phone and alt phone.

**Comment by bengolder** [comment]
related to #447 & #448
