### ISSUE TITLE
Add task queue setup to getting started documentation

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#452]
## Task Queue

```bash
brew install rabbitmq
```

Run workers

```bash
celery -A project worker -l debug
```

Add to `/usr/local/sbin` to `PATH`
```bash
PATH=$PATH:/usr/local/sbin
```

```bash
rabbitmqctl status
rabbitmq-server
brew services start rabbitmq
```

**Comment by jennifermarie** [comment]
Celery / Rabbit Refresher notes:

`brew services start rabbitmq` 
 run rabbit run

`rabbitqctl status`
 check rabbit status

`celery -A project worker -l debug`
 start running celery

in shell:

`from project import celery
celery.debug_task.delay()`

Out: `<AsyncResult: 1796a71b-1918-48af-8e92-4ad5a29db081>`

 sample to get direct-from-celery


in shell:
`from intake import tasks
tasks.log_to_mixpanel.delay(15, 'celery_event', {})`
Out: <AsyncResult: 322e6794-d846-439e-a6e5-1efce3149a0b>

 sample to log to mixpanel on delay
