### ISSUE TITLE
Expand "additional info" box within status notification checklist

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#456]
Can we make the free form text box bigger so attorney's understand they can enter more text?

**Comment by jazmynlatimer** [comment]
![screen shot 2017-02-24 at 9 21 48 am](https://cloud.githubusercontent.com/assets/5255453/23313470/b4cbb876-fa72-11e6-978b-93af16be721c.png)
I think the "additional info" box is already pretty big. This is the live version @sarahlizwhite - I know the mockups have a smaller "additional info" box.

**Comment by sarahlizwhite** [comment]
this is optional and I think already resolved ,we showed them an old screenshot

**Comment by bengolder** [comment]
Closing. we can reopen if it comes up again.
