### ISSUE TITLE
Increase Behave Test Coverage for any missing critical user tasks

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#481]
With #461 in place, it would be useful to create acceptance tests that attempt key tasks and workflows that are important for users to be able to do. These should be run on PR heroku apps.

**Comment by rossettistone** [comment]
@bengolder Do the `behave` tests cover this? Or is this suggesting something one step further?

**Comment by bengolder** [comment]
@rossettistone correct. I changed the title to be more relevant to current goals.
