### ISSUE TITLE
Attach mailing list to key alerts

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#487]
with #486, based on recent errors.

**Comment by joduinn** [comment]
@bengolder @jennifermarie are all alerts that used to go to you individually now instead going to the clearmyrecord-alerts@ email list (and from that to slack)? 

Anything left to do here before we close?

**Comment by jennifermarie** [comment]
I believe so! Tagging @bengolder to confirm.

**Comment by bengolder** [comment]
This is done in principle (the settings were changed) but we haven't received key alerts since that change. We should test to confirm that they work as intended. I will temporarily set alerts to a lower threshold and then report back based on the results.

**Comment by bengolder** [comment]
alert service | set to email list? | tested with actual alert? | barriers
-------------|----------------|-----------------------|-----
Heroku | Yes | Yes | None
Django | Yes | Yes | None
New Relic | Yes | Yes | None

**Comment by bengolder** [comment]
Heroku's alert email confirmation code doesn't seem to be making it to the mailing list.

**Comment by joduinn** [comment]
Just finished group meeting with @bengolder @jennifermarie @glassresistor . Waiting for one last test-event to fire (see comment above), and then we can declare this ticket all done!

**Comment by mikela** [comment]
Hey @joduinn, you probably didn't mean to mention me, you may want to mention the proper person. Cheers!

**Comment by joduinn** [comment]
> Hey @joduinn, you probably didn't mean to mention me, you may want to mention the proper person. Cheers!
@mikela sorry about that - I actually meant to mention @glassresistor .

**Comment by bengolder** [comment]
We received a Heroku alert this morning, so all the channels have been tested. I'm closing this issue and linking open related issues here:

- #497 Audit existing alerts
- #464 Add monitoring & alerts for task queue size
- #498 Set up any new alerts that are desired
- #499 Change alert destination (I think this might be done)
- #504 Review user activity alerts
- #598 Set up customer service response time alerts
