### ISSUE TITLE
Delegate Q1 Status Notifications Report Pieces

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#495]
One of our key deliverables for Q1 was a report on Status Notifications, describing the rollout, adoption, and the knowledge gained. I (Ben) bottom-lined this, but want to check-in and confirm which portions I should handle, and which portions others would like to take on.

**Comment by jazmynlatimer** [comment]
I'll have a lot of this done from the research debrief, FYI. So we should just start from that.

**Comment by bengolder** [comment]
Ben will pull numbers for various questions and add them to Jazmyn's report.
