### ISSUE TITLE
Figure out AWS S3 account management for CMR

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#513]
Currently CMR uses ben's private non-org account
Perhaps use bucketeer

**Comment by joduinn** [comment]
@bengolder 
1) what is the account# of the current non-org AWS account? If nothing else, in the short term, we can move billing for this to CfA, so you are not financially out-of-pocket.

2)  what exactly is in this account? If it is "only" s3 buckets, we can move these buckets into a CfA-owned-and-paid-for account and plan a switchover. If there are other things running in the same account, we should talk through the details first.

**Comment by bengolder** [comment]
This has been mostly handled, and deployments were migrated to bucketeer. The only remaining task is to remove the outdated credentials
