### ISSUE TITLE
Have Application Queues for each organization 

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#529]
Currently the relationship and ordering between each org and it's set of application is implicit, based on when the application was submitted. We then categorize these applications based on when their URLs were accessed by a user, and status updates.

A common interaction paradigm in case management applications is to have "queues" that users can sort cases into. Queues are often, though not necessarily, customizable. The ability to create and name queues allows case managers to have explicit workflows and share the load or delegate tasks to other people. It creates an explicit ordering, allowing them to see what is next and which stage a case is in.

I think this would be useful. It would help with #451 and #528

**Comment by bengolder** [comment]
Here is a sketch of a possible model:

```python
from django.db import models


class Queue(models.model):
    slug = models.SlugField()
    name = models.TextField()
    description = models.TextField()
    organizations = models.ManyToManyField(
        'user_accounts.Organization', related_name='queues')
    applications = models.ManyToManyField(
        'intake.Application', through='intake.QueuePosition`)
    is_default_inbox = models.BooleanField(default=False)
    is_custom = models.BooleanField(default=False)
```

**Comment by TiffanyAndrews** [comment]
Define more explicit application states: 'NEW' 'RECEIVED' etc.
Create backend changes for tracking application status in the queue.
