### ISSUE TITLE
Remove unused pdf-handling code

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#53]
Remove any unused models.
Refactor views and services where feasible.

**Comment by rossettistone** [comment]
@bengolder It looks like this might have happened. Is that true, or are there still elements of PDF handling that are inside the `intake` codebase?

**Comment by bengolder** [comment]
@rossettistone yes, I think all the bundling, models and async tasks around this are still in intake.

**Comment by bengolder** [comment]
This is done.
