### ISSUE TITLE
UX/design update on all CMR views

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#552]
_From @jazmynlatimer on August 30, 2016 20:43_

Go through product and make UX/Design updates on all pages. Recommendations in this doc: https://docs.google.com/document/d/1R1MFvU6WK4muDxD2zyjImgIgl_yEZyGlvKnrNPrNdBM/edit

_Copied from original issue: codeforamerica/clear-my-record#343_

**Comment by TiffanyAndrews** [comment]
_From @jazmynlatimer on September 22, 2016 0:11_

- [ ] landing page
- [ ] application
- [ ] confirmation page
- [ ] privacy page
- [ ] Applications index
- [ ] Login
- [ ] Org Admin
- [ ] Application view
- [ ] Bungle Application view
- [ ] Org admin settings

**Comment by bengolder** [comment]
This should be split into smaller issues.
