### ISSUE TITLE
Make a spanish translation of web intake form

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#555]
_From @bengolder on March 14, 2016 22:5_

- [ ] Finish internationalization #57
- [ ] Export  spanish translation files
- [ ] Prepare instructions/documentation for translator
- [ ]  Hire a translator

_Copied from original issue: codeforamerica/clear-my-record#97_

**Comment by sarahlizwhite** [comment]
Counties that have requested: 

1. San Diego 
2. Tulare (not a CMR user)
3. Solano
4. Contra Costa (has asked three times)
5. Ventura
6. Santa Barbara

**Comment by bengolder** [comment]
I met a qualified translator (a very experienced court interpreter who has a done a lot of translating relating to social services)
