### ISSUE TITLE
Set up content testing pipeline

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#557]
_From @bengolder on April 18, 2016 20:43_

- write for low literacy levels
- check for other useful automated feedback

_Copied from original issue: codeforamerica/clear-my-record#180_

**Comment by bengolder** [comment]
Perhaps have a command line script that can analyze our writing and give us feedback on reading level or other copy analysis on the site, with the goal of helping us simplify language and improve our writing.
