### ISSUE TITLE
Unique URLs for Checkr Referral partnerships

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#565]
Jenny and I chatted with Checkr today and learned they are actively doing outreach to expand referral partnerships to other clients. As they add new customers to this partnership, we'd like to create unique urls per partner so we can better track traffic and conversation rates for different partnerships. 

Please create unique urls for:
Uber
DoorDash
DELIV

I will send back to Checkr when created.

**Comment by bengolder** [comment]
Showed @sarahlizwhite how to create unique URLs today, let me know if you need any more help.
