### ISSUE TITLE
mock fillable pdf has no organization foreign key

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#586]
in our `load_mock_data` command, we use `mock.fillable_pdf()` to mock out a fake fillable pdf. But this is never linked to San Francisco's account, so it can't find the pdf to fill and just loads the default app detail page instead. To fix this, we just need to link the mock fillable pdf to San Francisco.

**Comment by rossettistone** [comment]
@bengolder Is this still relevant? If so, seems like a little chunk of tech-debt to consider for support mode.

**Comment by rossettistone** [comment]
After convo with @bengolder, it seems like this *could* still be true. We'll dig into the code later to confirm.

**Comment by bengolder** [comment]
This was fixed
