### ISSUE TITLE
Draft 2 of CMR user personas and design principles

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#591]

**Comment by jazmynlatimer** [comment]
Synthesize research from last year with most recent applicant and attorney research insights and produce more fine-tuned user personas that we can start including in our discussions.

See most recent user insights here: 
- Attorney Research 3/2017 - https://drive.google.com/open?id=1InWe8kGCU_If_VUCcwj7yjTsBHGnokMaice7Nzb8alo
- Applicant Research 3/2017 - https://drive.google.com/open?id=1dTJ85xCiDWnxaF0cgS444WKQCgVrRkaU_-gc5-wN15w

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer Have you finished writing the user personas? If so, can you link is here?
