### ISSUE TITLE
Add autocomplete attributes to form

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#60]
See here for more details:
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill?hl=en

For address:
- `autocomplete="shipping street-address"`
- `autocomplete="shipping locality"`
- `autocomplete="shipping region"`
- `autocomplete="shipping postal-code"`

Phone: `autocomplete="tel"`

**Comment by spencerhitch** [comment]
This seems to already be working in chrome for me:

![image](https://cloud.githubusercontent.com/assets/3680815/17599318/5c23b746-5fb3-11e6-927f-26081a198b94.png)

**Comment by bengolder** [comment]
Yeah, autocomplete works already on some fields, but not others. This is more about updating the html to meet more widely used standards so that the browser can fill out more and is less likely to have to guess.
