### ISSUE TITLE
Revise automated follow ups w/ current Status Notification conflict

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#601]
If they sent SN, don't send auto followup.

**Comment by bengolder** [comment]
For the follow up query, simply exclude applicants who have received status updates.

**Comment by bengolder** [comment]
This is going to require more refactoring than expected.

To do this correctly, we will need to check each `Application` for existing status updates, and then bundle, by submission, the notifications for any `Application` objects that lack status updates

**Comment by bengolder** [comment]
Just got a request from LH to change this ASAP

**Comment by bengolder** [comment]
Restrict to EBCLC and San Francisco specifically. Do not send followups for other orgs.
