### ISSUE TITLE
Write Partnerships page HTML using CfA styleguide

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#613]
Mocks: https://drive.google.com/drive/u/0/folders/0B3BLnlbsdQ_hdU5JRWZlcVVEWFk

**Comment by jazmynlatimer** [comment]
depends on #614

**Comment by bengolder** [comment]
This title feels too broad. I'm going to rescope this to be specifically for the partnerships page, which will be the first page that uses the new styles

**Comment by bengolder** [comment]
@jazmynlatimer could you link the mocks for this?

**Comment by jazmynlatimer** [comment]
Mocks: https://drive.google.com/drive/u/0/folders/0B3BLnlbsdQ_hdU5JRWZlcVVEWFk
