### ISSUE TITLE
Spike out branch with CfA styles

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#614]
@norrishung

**Comment by bengolder** [comment]
This was not as simple as hoped. In short, using npm installs with our current asset pipeline only utilizes npm versions of packages, which are out of sync with canonical versions. Ideally, we should just use the canonical versions.

Here are the next steps to try to integrate:

1. Look into using multiple heroku buildpacks to install frontend tools (such as sass) on heroku.
2. Look into using django-compressor or django-pipeline.

**Comment by bengolder** [comment]
@glassresistor is testing out heroku buildpacks on #717

**Comment by bengolder** [comment]
Closed with the creation of #838
