### ISSUE TITLE
Switch APD's email address from LR's email to their general email address

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#617]
This needs to be done by LR's last day on 4/7

**Comment by bengolder** [comment]
@jazmynlatimer if I send an account invite to that email, will someone be able to respond and set the password?

**Comment by bengolder** [comment]
send email to LR & cc SW/JL

**Comment by bengolder** [comment]
sent invite, waiting for switch

**Comment by bengolder** [comment]
Looks like the account was not created, because #676 .

Resent invitation, asked LH to logout before accepting invite.
