### ISSUE TITLE
Print flyers and prep for CoCo record clearance fair on 4/8

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#636]

**Comment by bengolder** [comment]
- [ ] set up a unique code for this event (`https://c4a.me/cococlear/`)
- [ ] track the time we put in, treat it like a mini-experiment

**Comment by jazmynlatimer** [comment]
Sarah created a special link for CoCo fair flyers: www.c4a.me/ccclinic

**Comment by jazmynlatimer** [comment]
Jenny printing flyers and banner
