### ISSUE TITLE
Make sandbox mock DB

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#643]

**Comment by bengolder** [comment]
Look at the inclusion of #599

**Comment by bengolder** [comment]
We should check if this is truly needed before doing it.

**Comment by TiffanyAndrews** [comment]
Not needed at this time!

**Comment by bengolder** [comment]
Reaffirming the need for this, with a different use case:

**As a CMR dev, I want to test database changes on production data schemas without requiring access to sensitive data**

@jennifermarie & I discussed a method in which we could run a command regularly that would create a copy of the production database and replace all database columns containing PII. We could run it manually and/or on a regular basis
