### ISSUE TITLE
Shut down legacy 3rd party services

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#657]
Shut down 3rd party services _that are no longer in use._

- [ ] Typeform
- [ ] Seamless Docs

**Comment by rossettistone** [comment]
@bengolder I suspect these are gone now. Can you confirm?

**Comment by bengolder** [comment]
We definitely need to do this.

**Comment by TiffanyAndrews** [comment]
@bengolder can finish this ticket by Friday. Mikela and Laura don't have admin access to seamless docs and typeform.

**Comment by bengolder** [comment]
I've deleted all data from both Typeform and Seamless Docs.
I delete the SeamlessDocs account.
I've written an email to Typeform to request that they the account (which is just an empty account now)
