### ISSUE TITLE
make forms and fields into models, as if we were making a form builder app

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#66]
To support multiple counties, we need a way for someone to apply for more than one county.
In particular, we need a way to combine the requested fields for both the counties.

If we don't find a simple way to designate and configure fields on each county, and then to programmatically combine fields from multiple counties, the amount of work will grow exponentially.

Ideally, fields for a county should be configured at the admin level

Field:
- label
- help_text
- type
- required

**Comment by rossettistone** [comment]
@bengolder While this isn't handled at the admin layer (though that was a great idea!), it seems like the present level of abstraction on form building reflects an implementation of this idea. Can we close this one out?

**Comment by bengolder** [comment]
Yeah
