### ISSUE TITLE
Plan redesign of implicit receipts and bundles

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#671]
Taking into consideration usage of Status Notifications and the missing applications issue we had with SF apps on 4/4/17.

**Comment by TiffanyAndrews** [comment]
This issue is linked with
- [ ] #529
- [ ] #528 
- [ ] #451

**Comment by jazmynlatimer** [comment]
From Design/Research meeting on Friday - I'm starting this by writing some problem statements we're trying to solve for, doing an ideation session, and building mockups to test with partners when I test Status Notifications prototypes
