### ISSUE TITLE
User testing of Status Notifications v1.5 mockups

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#688]

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer  can you add screenshoots of the mockups to this issue?

**Comment by jazmynlatimer** [comment]
@TiffanyAndrews they are all in #589

**Comment by jazmynlatimer** [comment]
Tested with CCPD on 4/14 - notes here: https://drive.google.com/open?id=1oDegK5W_PiLFQWqsAob9aKJ7qhRhESQKZ4n8LvdKn18

**Comment by jazmynlatimer** [comment]
Iterating mockups to include Status Notifications for multiple cases and Updating statuses w/o sending a message to applicants
