### ISSUE TITLE
Document CMR feature usage by county partner

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#690]

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer  is this for status notification? or something else? there is already an issue #580 for this.I will be pulling/ creating a dataclip for this .

**Comment by jazmynlatimer** [comment]
@TiffanyAndrews this isn't related to status notifications. This was a task from our post-mortem last week. You asked if you could see which county partners use which parts of CMR so we know who we're affecting when we make decisions about different features.
