### ISSUE TITLE
mockups for new apps index page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#704]

**Comment by jazmynlatimer** [comment]
Linked to issues #702 and #703

**Comment by jazmynlatimer** [comment]
Thinking something like this...
![screen shot 2017-04-11 at 1 27 45 pm](https://cloud.githubusercontent.com/assets/5255453/24929421/b9bab6a4-1eba-11e7-9996-bfe05d5fb0fb.png)
![screen shot 2017-04-11 at 1 27 54 pm](https://cloud.githubusercontent.com/assets/5255453/24929425/bca3d724-1eba-11e7-82c6-e66931f20da2.png)
![screen shot 2017-04-11 at 1 27 33 pm](https://cloud.githubusercontent.com/assets/5255453/24929432/c0219ada-1eba-11e7-843f-0ddcc61cdf99.png)
![screen shot 2017-04-11 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/5255453/24929433/c215999a-1eba-11e7-8fdc-659e3ab2cde0.png)

**Comment by jazmynlatimer** [comment]
Some other options...
![screen shot 2017-04-11 at 4 44 51 pm](https://cloud.githubusercontent.com/assets/5255453/24935342/4d191cc2-1ed6-11e7-8def-17e5870e7039.png)

Or, to use the tabs in the GCF styleguide: https://getcalfresh.org/styleguide
![screen shot 2017-04-11 at 4 44 59 pm](https://cloud.githubusercontent.com/assets/5255453/24935355/62da4612-1ed6-11e7-8534-6e6edab29f88.png)
![screen shot 2017-04-11 at 4 45 06 pm](https://cloud.githubusercontent.com/assets/5255453/24935356/62dca75e-1ed6-11e7-9c56-a2dc17708606.png)
![screen shot 2017-04-11 at 4 45 14 pm](https://cloud.githubusercontent.com/assets/5255453/24935354/62d7d81e-1ed6-11e7-8083-4de7402dbeef.png)

I prefer the tabs, especially if we're trying to go for uniformity across products...

**Comment by jazmynlatimer** [comment]
Interactive prototype: https://invis.io/SHBA7817W
