### ISSUE TITLE
Possible lost sms messages

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#706]
@sarahlizwhite reported that confirmation messages aren't being sent to her phone

Tested with 2 other phone numbers and they seemed to be working fine.

Front shows that the messages were sent to her phone, but she is definitely not receiving the texts.
Her phone is working for texts sent from other sources.

This might be an issue with particular carriers, a class of phones, or simply this one phone.

**Comment by sarahlizwhite** [comment]
They eventually came through at 12:30am the next day. Maybe there's a limit to how many CMR texts I can get in day?

**Comment by bengolder** [comment]
I'm going to close this as resolved for now. We can reopen if we see any further indications of lost sms messages.
