### ISSUE TITLE
Revise probation question

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#724]
*FINAL DESICION R/W*
`"If you are on probation or parole, what county is it in?"`

------------------------------------------------------------
Revise probation question to ask specifically what county they are on probation in. 

Something like, "If you are on probation or parole, in which county is it in?". The group felt "where is it?" to be too vague.

**Comment by jazmynlatimer** [comment]
Final wording for everyone that has this question: "If you are on probation or parole, what county is it in?"

**Comment by sarahlizwhite** [comment]
ACTUAL FINAL : "If you are on probation or parole, which counties is it in?"
