### ISSUE TITLE
Clarify and break up income Q:

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#737]
have drop down or check boxes for type of income [spouse, job, government benefits, etc]

**Comment by sarahlizwhite** [comment]
Santa Clara would like to go this route too. They need to differentiate and be clear on spousal vs. household income so as not to disqualify anyone. 

They would also like to add help text to HH income question that defines a HH (single adult or legally married/domestic partnered couple). They can support a single person living with their boyfriend and don't want to capture non-legal partner income. 

https://docs.google.com/document/d/1wzM2-cU85glW9dITLUTFQIe7WRZ5tfo4s4zas16vvuY/edit

**Comment by TiffanyAndrews** [comment]
@jazmynlatimer  ?

**Comment by jazmynlatimer** [comment]
Does this issue refer to this question?
![screen shot 2017-04-28 at 12 04 30 pm](https://cloud.githubusercontent.com/assets/5255453/25543317/e0ea24fa-2c0a-11e7-89e0-872559f5a965.png)

**Comment by jazmynlatimer** [comment]
And, if we want to put in checkboxes... why? and what options do they think they need?

**Comment by jazmynlatimer** [comment]
For now: Just add "spouse, legal partner" to help text for the question "Where does your income come from

For later: When we do the Form redesign in Q3, we'll try to remove as much free form text as possible and maybe implement checkboxes.
