### ISSUE TITLE
keep the original user's name on actions they've completed

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#740]
Lindsay's name in APD login has changed to Sue, even though Sue wasn't the person who made old status updates. We should keep the original user's name on actions they've completed so that it doesn't confuse new users (for example - now Sue might think she made status updates that she actually did not)

**Comment by jazmynlatimer** [comment]
![screen shot 2017-04-18 at 1 36 56 pm](https://cloud.githubusercontent.com/assets/5255453/25151979/70e62274-243c-11e7-998c-8299f5baf5e2.png)
 For example, Lindsay was the user who actually made this status update. But when we changed the primary username to Sue, it changed Lindsay's name all throughout the product.

**Comment by bengolder** [comment]
This is because they were using the same login account. We should encourage partners to use accounts linked to individuals for logging in.
