### ISSUE TITLE
Enable daily e-mail notifications for Solano user

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#741]
https://docs.google.com/spreadsheets/d/1IEXUinWasKbEKcyEKh2NyUxczQcVBqRmkfFO33DnOvI/edit#gid=0

**Comment by sarahlizwhite** [comment]
@bengolder will you also let me know if this will be activated so she gets e-mail starting tomorrow. i'd like to be able to tell her when this will start.

**Comment by bengolder** [comment]
Done. they will get daily emails starting tomorrow morning.
