### ISSUE TITLE
Add Compressor and integrate with testing and deploy

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#745]
- [x] Add Ruby and Node to heroku
- [x]  Add requirements
- [x]  Add Compressor and configure 
- [x] Reorganize CSS and JS if necessary
- [x] Hijack collectstatic and add compressor

Optional run collectstatic on Travis

**Comment by joduinn** [comment]
per meeting, @glassresistor will link to other tickets - expect to complete by mid-week.

**Comment by glassresistor** [comment]
Its currently working locally and on travis but Heroku has a different path for node_modules

**Comment by glassresistor** [comment]
- [ ] Copy bootstrap css and fonts into Intake static files
- [ ] Remove fonts symlink
- [ ] Pin bootstrap node version so js and css dont get out of sync
