### ISSUE TITLE
Ventura Contact info for partner page & create login

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#751]
Website: https://www.pubdef.countyofventura.org/

E-mail: see partner user spreadsheet

No phone please

Address: 

Hall of Justice
800 S. Victoria Avenue
Room # 207
Ventura, CA 93009
(805) 654-2201

**Comment by sarahlizwhite** [comment]
e-mail has not been set up yet, do not create account quite yet.

**Comment by jennifermarie** [comment]
Following up on this: which email should be used? Is it `clear@`?

Also: the organization has a phone number set already; should we clear it?

**Comment by sarahlizwhite** [comment]
Use clear@, remove phone number per partner request.
