### ISSUE TITLE
extend Heroku logs beyond 1,500 lines

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#755]

**Comment by glassresistor** [comment]
So Heroku log drains are designed to push data to normal Syslog servers.  Im most familiar with rsyslog but will ask @joduinn what he thinks the fastest route to Syslog on Amazon.

I didn't see a rsyslog AMI in the marketplace but its pretty straight forward to setup and ansible seems to some good roles for it(https://github.com/debops/ansible-rsyslog).
