### ISSUE TITLE
Some exceptions are failing silently

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#757]
Hypothesis:
without a try/except clause for handling exceptions in `View.dispatch()`, requests fail silently and exceptions are not properly raised.

**Comment by glassresistor** [comment]
It something isn't raising an error putting a try except on it will not help since its not signaling a failure.

If you can find the line that should be failing we can triage why.

**Comment by rossettistone** [comment]
After convo with @bengolder, there's not enough info here for us to remember what we were trying to fix. Closing for now.
