### ISSUE TITLE
Organize Jinja Templates

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#761]
Currently the Jinja templates are all in `templates/`

As a developer I would like to be able to quickly find a template based off its name and location.

I suggest that we split up the templates into multiple directories.

Because most everything is in the intake app for now, everything except the actual base should be in `intake/templates/intake` and base should be `project/templates/base.jinja`

Some cleanup is just renaming files for clarity for instance `admin_base.jinja` should just be `base.jinja` because everything uses it.

It would be great in the long run for it to look something like this
```
project/templates/base.jinja

intake_admin/templates/intake_admin/base.jinja  #intake_admin b/c admin is taken
intake_admin/templates/intake_admin/single_column.jinja
application/templates/application/base.jinja
```
Doing this well would mean breaking intake out into 2 or 3 applications of its own but should be doable in small pieces.

**Comment by bengolder** [comment]
> breaking intake out into 2 or 3 applications of its own but should be doable in small pieces.

Splitting intake into multiple sub-apps sounds like an issue all it's own.

**Comment by glassresistor** [comment]
For now we should move templates into intake and make sure the templates are in templates/intake so they are properly name spaced.

I'm happy to wait to break out the intake app into smaller parts in the future.

The main thing is that having things in the root portion of templates in the root directly isn't considered safe .
