### ISSUE TITLE
Health Check URL

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#768]
*As CfA engineering staff I want a simple URL to use for checking CMR's health, so I can monitor uptime without cluttering analytics* [0 days total]

- [ ] Create `/health` url that simply returns a 200 status code on `GET`. No template or analytics necessary (0 days)
- [x] Turn on newrelic uptime ping (0 days)

**Comment by bengolder** [comment]
Should we create urls for other status codes, to ensure errors and other statuses are returned correctly? Perhaps a page that can take a simple `POST` or `GET` with query params and returns corresponding status codes?

Should we return any other data on our health check URL?

**Comment by glassresistor** [comment]
Having a 200 and 500 view is great.  I don't see a need for the others and
using get to determine what to return doesn't help us since its artificial.
