### ISSUE TITLE
Pre-render PDF bundles

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#77]
The current process is creating critical errors, see #76.

Before sending out bundles, we can pre-render PDFs that can be served as static files. This will make them much faster to access.

**Comment by bengolder** [comment]
- Create a FilledPDF model (with foreign keys to a Fillable PDF and a submission)
- Create a PDF bundle model (links to many submissions, and one fillable PDF)
- generate the pdf and store it on the bundle
- we should perhaps do this with individual submission PDFs as well.

A bundle is kind of just an inbox. That inbox may need to have a pdf representation of itself.

Whether or not PDFs should be generated can be determined at the same moment that the target organizations are determined. Only some orgs will use filled pdfs for their incoming referrals.

**Comment by bengolder** [comment]
This is most properly handled as a task queue, one candidate might by [Advanced Python Scheduler](https://apscheduler.readthedocs.io/en/latest/)

**Comment by bengolder** [comment]
Here are some of the relevant pieces of code:

_Ways to detect if a submission will need a pdf to be rendered_
- If a submission is going to any organizations that have `intake.models.FillablePDF`s, then those pdfs forms should be pre-rendered and stored as `FilledPDF` instances.
- `user_accounts.models.Organization.has_a_pdf()` returns `True` if an org has any associated `intake.modelsFillablePDF` instances
- `user_accounts.models.Organization.pdfs` is a reverse foreign key for `intake.models.FillablePDF.organization`

In `intake.models.FillablePDF`:

``` python
class FillablePDF(models.Model):
    . . .
    organization = models.ForeignKey(
        'user_accounts.Organization',
        on_delete=models.CASCADE,
        related_name='pdfs',
        null=True
        )
```

_Places to prerender PDFs (or add tasks to a queue to do so)_
- `intake.views.MultiStepApplicationView.save_submission_and_send_notifications` - A place to either create the FilledPDF instance or schedule to task to do so. The best place to create the FilledPDF instances, would presumably be _after_ saving the submission. Once a submission is saved, it should have organizations associated with it (through `organizations` M2M field, but this assignment of orgs to submissions is still being implemented).
- `intake.submission_bundler` - a place to build bundles, would be a good location to check if submissions need pdfs, and to concatenate FilledPDFs into FilledPDFBundle instances. The submission bundler's entry point is `submission_bundler.bundle_and_notify()`, which is called from `intake.management.commands.send_unopened_apps_notification`. Since this is called by a command-line task, this is less time-sensitive than the views.

_Places to serve pre-rendered pdfs instead of rendering them on the fly_
- `intake.views.FilledPDF`
- `intake.views.FilledPDFBundle`

**Comment by glassresistor** [comment]
1.  (DONE) Update cronjob bundler to produce ApplicationBundle model and (ben lookup concat pdfs)
2. (DONE) Add `get_absolute_url` to ApplicationBundle
3.  (DONE) Update notification templates to take a bundle 
4.  (DONE) Create new ApplicationBundleView to take pk for bundle and return bundle detail
5.  (DONE) Leave old view make sure it works
6. (DONE) update mark viewed notification with new bundle url
7.  (DONE)Added backfill migration for filledpdf.
8.  Add tests
   - (DONE) Test that filledpdf instances are created when saving a new FormSubmission
   - (DONE) Test bundler creates application bundle model instance
   - (DONE) Test AppllicationBundleDetail(View) returns 200 on id existing
   - (DONE) Test returns 404 if non existent
