### ISSUE TITLE
Clarify HH Income question

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#771]
*FINAL DESICION R/W*
`Question: "What is your monthly income?"`
`Help text: "Include your spouse or legal partner's income. Your best estimate is okay."`

-----------------------------------------------------------
Request from Santa Barbara & Santa Clara. 

Need to ensure we are capturing a single person's monthly income and legal partner/married couple monthly income. 

Household is jargony - Santa Clara worried about applicants disqualifying themselves by listing non-legal partner income as part of their "household".

**Comment by jazmynlatimer** [comment]
Question: "What is your monthly income?"
Help text: "Include your spouse or legal partner's income. Your best estimate is okay."

Tried a bunch of ways of not using help text, but this was the clearest I could come up with. All other ways made the question long and confusing (ex: "How much do you and your spouse or legal partner (if you have one) make each month?"  or  "What is the monthly income of you and your spouse or legal partner?" :/ )

**Comment by jazmynlatimer** [comment]
Updated in multi-county spreadsheet
