### ISSUE TITLE
Write audit log functions (subtask of #658)

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#779]
**Goal:** To create an automated audit trail and that meets or exceeds the requirements of CJIS
### Details

CJIS specifies the following audit logging requirements for handling of CJI:

https://gist.github.com/bengolder/6cd23f0ebff741c79b6b39b45d3e5a56

This tasks assumes that we would log from the application layer to standard out, pushing our logs into our standard log stream to be directed to appropriate sources.

Create action-specific audit logging functions that can be reused in views and the django admin.
One for each major generic CRUD view.

**Comment by jennifermarie** [comment]
Some learnings from the audit/access spike:

We have an existing `format_and_log` function, but it may be overly generic. If we define CRUD-action-specific logging functions, we can log the right information in the right context.

As with `format_and_log`'s current use in the events service, we can use serializers to limit to audit-log-specific fields (to avoid PII).

**Comment by bengolder** [comment]
@rossettistone & I evaluated more libraries to find simpler, more maintainable ways to implement this task. We found [django-easy-audit](https://github.com/soynatan/django-easy-audit) which seems to do a decent job of logging what we need to log in a simple way

What it does:
- it records all major CRUD events, except "reads", in the database, including who performed them.
- by default it covers every model, but it is simple to configure to exclude any models
- it stores the full state of the model
- it figures out who performed the task by implementing middleware and storing the current request
- it also records login events, such as successful and unsuccessful attempts to log in to the application.
- automatically integrates with actions performed through the Django admin (so we wouldn't need to write new integrations to cover the admin)

**Comment by bengolder** [comment]
We have determined that django-easy-audit, while good at most things, appears to falsely attribute some automatic non-user actions to users who recently logged in. We have identified why this happens, and we are attempting some small patches.
