### ISSUE TITLE
heroku alerts should go to clearmyrecord-alerts instead of individual emails.

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#794]

**Comment by glassresistor** [comment]
New Relic Alerts now go to clearmyrecord-alerts. The only way I was able to do this for Heroku was to add it as a collaborator.  Having discussed with the team that was determined unacceptable.

@bengolder might have found a way to do this but I was not able to find it.

**Comment by bengolder** [comment]
Double checked. This is done. The UI path in Heroku is:

Dashboard > cmr-prod > Metrics > Configure Alerts > Monitor Response Times > Alert Notifications > Add Email Address > (add the email) > (check the box that says "Send notifications to the additional email address:")

![screen shot 2017-08-30 at 1 38 54 pm](https://user-images.githubusercontent.com/451510/29893945-998e71b2-8d88-11e7-81fe-aead2d4aeaaa.png)
