### ISSUE TITLE
Refactor views for consistent access control checks

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#800]
Subtask of #658 

We need to refactor our views, including django admin, such that each includes an explicit access control policy and logs if necessary. For public views, this should be implemented with some easy-to-implement wrapper that exempts them from logging and explicitly states that they allow all access.

- [ ] *All relevant DjangoAdmin views*
- [ ] *All of our views*
- [ ] *All relevant 3rd party views (invitations, accounts)*

In our views, make use of:
- a `permission_classes` attribute on view classes, that should be a list of `Permission` classes
- make any specific `Permission` policies needed, use existing Permissions from Django REST Framework wherever possible.
- make base views or mixins to assist with our views
- use `get_queryset` and ensure that it does not use query filtering to check permissions. Let the Permission class do the filtering and checking.
- don't override `.dispatch`, instead let base views create the hooks necessary for any request rerouting.
- use exceptions and exception handlers to say that access is not allowed
- try to make more use of Django's generic views where possible

For DjangoAdmin views:
- use `log_addition` and `log_change` to log write actions (and deletion)
- use `get_queryset` to log read actions

**Comment by bengolder** [comment]
We will use our tests to get a more granular list of the specific views that have been given fancy security logging and which have not.

**Comment by jennifermarie** [comment]
Existing Permissions classes:
    - `AllowAny`
    - `IsAuthenticated`
    - `IsAdminUser`, basically the same as `is_staff`
    - `IsAuthenticatedOrReadOnly`
    - `DjangoModelPermissions`, uses a permissions map for request types to pull up django's default permissions. This requires the view to have either a `.get_queryset` method or a `.queryset` attribute defined.
    - `DjangoModelPermissionsOrAnonReadOnly`
    - `DjangoObjectPermissions`, requires an object-permissions-enabled backend, such as Django Guardian.

**Comment by jennifermarie** [comment]
```python
# example permissions map for DjangoModelPermissions
    perms_map = {
        'GET': [],
        'OPTIONS': [],
        'HEAD': [],
        'POST': ['%(app_label)s.add_%(model_name)s'],
        'PUT': ['%(app_label)s.change_%(model_name)s'],
        'PATCH': ['%(app_label)s.change_%(model_name)s'],
        'DELETE': ['%(app_label)s.delete_%(model_name)s'],
    }
```

**Comment by jennifermarie** [comment]
#### How DjangoREST views interface with permissions

```python
# methods on rest_framework.views.APIView
class APIView:
     def permission_denied(self, request, message=None):
        """
        If request is not permitted, determine what kind of exception to raise.
        """
        if request.authenticators and not request.successful_authenticator:
            raise exceptions.NotAuthenticated()
        raise exceptions.PermissionDenied(detail=message)
    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        return [permission() for permission in self.permission_classes]
    def check_permissions(self, request):
        """
        Check if the request should be permitted.
        Raises an appropriate exception if the request is not permitted.
        """
        for permission in self.get_permissions():
            if not permission.has_permission(request, self):
                self.permission_denied(
                    request, message=getattr(permission, 'message', None)
                )
    def check_object_permissions(self, request, obj):
        """
        Check if the request should be permitted for a given object.
        Raises an appropriate exception if the request is not permitted.
        """
        for permission in self.get_permissions():
            if not permission.has_object_permission(request, self, obj):
                self.permission_denied(
                    request, message=getattr(permission, 'message', None)
                )
```

**Comment by jennifermarie** [comment]
#### Utilizing DjangoREST permission checks on a child view

```python
class ApplicationDetailView(BaseAuditableView):
    permission_class = [
        StaffOrApplicationOrganizationMatchesUser # we can create custom permission checks
    ]
    def get_queryset(self):
        return models.FormSubmission.objects.all()
    def get_context_data(self):
        # this would return any additional data for rendering
        pass
```

**Comment by jennifermarie** [comment]
^^ above samples drawn from audit/access spike documents
