### ISSUE TITLE
Fix 404s in logs (favicons in wrong locations, missing css, missing png files)

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#829]
During audit hour we were still seeing 404s on apple touch specific favicons.
These 404s should have stopped at 12:26 but are still being scene as late as 6:53

**Comment by glassresistor** [comment]
Doing some continued research I used browserstack to load the CMR on all IOS and Safari browsers.  Although so far none of triggered any favicon 404s(although many favicon 200s).
One problem that i'm hitting is that many of the browserstack instances(mostly older ipads and iphones) are either rendering blank pages or timing out.  The Ipad 2 is consistently spending a very long time loading the page and then either timing out or showing a blank page.  It is set to wait 10sec in between page loads so its not being over taxed.

**Comment by glassresistor** [comment]
After doing more digging almost all of the Iphone and Ipad instances on browser stack fail to load the main page.  Testing with Windows 10 browsers and OSX Safari work fine as well as Androids of multiple flavor.  I'm not sure if this is a Browserstack issue or if there are bigger issues with CMR itself.

Looking at the logs during my testing period I see some 404s on favicons but the IPs are ones which have been accessing the site for long before i was testing it.

Here is what CMR looks like
![screenshot from 2017-05-11 23 06 22](https://cloud.githubusercontent.com/assets/118663/25985515/bd50fb6e-369f-11e7-9608-e561eb86d6f9.png)
Vs Google.com
![screenshot from 2017-05-11 23 09 51](https://cloud.githubusercontent.com/assets/118663/25985516/be47753e-369f-11e7-9204-becaa8f8bcf3.png)

**Comment by glassresistor** [comment]
After much back and forth I've found that screenshot tests fail for CMR(not Google) on most iOS devices.  Strangely doing live tests on those same environments work.
While doing live testing on the iPhone6/5 and the Ipad2/3 I was not able to get a 404 on favicons to happen, nor did any of the screenshot tests.  This is leading me to believe that these are cached lookups and will dissipate so we see less/none next audit.

I'm not sure why browserstack is having timeouts on screenshots specifically for our page but others but so far i don't see a link.

**Comment by joduinn** [comment]
Per mtg, still seeing some errors, but much reduced. Possible browser caching issue? @glassresistor will talk with @bengolder to see what left to do before closing here.

**Comment by glassresistor** [comment]
@bengolder let me know what you think about browserstack timeouts and if you think waiting to see if we still get them next audit hour

**Comment by joduinn** [comment]
Found in triage. Leaving open until we see if we find anything in Monday's audit hour.

cc @bengolder

**Comment by glassresistor** [comment]
we found more 404s during the past audit hour
moving this to a new ticket to research and fix the problem

**Comment by joduinn** [comment]
Found in triage. Here's the list of specific files that have 404-ed  in the last 7 days:

```
$
$ cat CMR_404_logs.txt | grep -v "wp-login" |  | grep -v "wp-admin" | grep -v "tel:" | cut -d' ' -f9 | sort -u
path="/android-icon-48x48.png"
path="/apple-touch-icon-120x120-precomposed.png"
path="/apple-touch-icon-120x120.png"
path="/apply//license.php"
path="/apply//uploadify/uploadify.php?folder=/"
path="/browserconfig.xml"
path="/favicon.ico"
path="/ms-icon-150x150.png"
path="/partners//license.php"
path="/partners//uploadify/uploadify.php?folder=/"
path="/static/CACHE/css/afc3a1549e0f.css"
path="/static/css/main.5463f50044b8.css"
path="/static/css/main.c1c7f3d550b4.css"
path="/static/img/CMR_share.fad8481039e1.png"
path="/static/img/CfA_logo.2dec099b1e17.png"
$ 
$
```

Looks like there are two issues here:
1) @glassresistor can you verify which of the above "missing" favicon icons have already been uploaded, but in different locations? Once we know this, we can debug whether to move, to setup redirects or if needed, fix webserver configs.
2) @bengolder @jennifermarie : can you please fix the missing css and CMR/CfA images? If they are expected to not exist, we should track down where they are being referenced from.

Tweaking summary to match reality

**Comment by bengolder** [comment]
Linking sub issues:
- https://github.com/codeforamerica/intake/issues/872 (Serve `/favicon.ico`)
- https://github.com/codeforamerica/intake/issues/830 (social share card images are broken)

**Comment by glassresistor** [comment]
Thanks @bengolder 

I've confirmed that all of the favicons and the browserconfig.xml are in static files and properly linked from the templates.   One possibility is that not everypage on our domain is including the <links> in the <head> tag and so those pages are causing the 404s.  Another option is its simply some browsers/robots not respecting them.

**Comment by glassresistor** [comment]
Closing this because we now have actionable tickets and adding  #891
