### ISSUE TITLE
Investigate SF's duplicate applications problem

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#844]
Msg from SF partner:

I’m receiving a lot of duplicate applications this week. Today my email said I had 13 new applications but 10 of them were duplicates (a couple of those were duplicates of duplicates). It’s like the system isn’t registering that I’m opening my emails. Not sure if there’s anything that can be done but I figured it’s worth asking.

**Comment by bengolder** [comment]
I can verify that the applications that were opened were not marked as open. There is definitely a bug.

**Comment by bengolder** [comment]
It looks like some of the variants of bundle views (we have 5 variants of bundle views) are not properly marking applications as having been opened. This would affect other org users accessing certain bundle views. Writing tests to check all relevant views.

**Comment by bengolder** [comment]
New tests are written. Adding code for fixes.

**Comment by bengolder** [comment]
The tests are now passing and there is a PR up that includes the preliminary fixes. I'm going to do an additional pass to read over and consider if there are edge cases not covered by the tests.
