### ISSUE TITLE
Setup accounts for customer service ability

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#853]
#835 is a subtask of this

- [x] Jenny
  - [x] Front access
  - [x] Followup access in app
  - [x] Privacy training
  - [x] Ability to return calls
- [x] Jen
  - [x] Front access
  - [x] Followup access in app
  - [x] Privacy training
  - [x] Ability to return calls
- [x] Tiffany
  - [x] Front access
  - [x] Followup access in app
  - [x] Privacy training
  - [x] Ability to return calls
- [x] Sarah
  - [x] Front access
  - [x] Followup access in app
  - [x] Privacy training
  - [x] Ability to return calls

**Comment by rossettistone** [comment]
@bengolder It looks like this issue might have been completed - or very nearly! Can we close?
