### ISSUE TITLE
Add status " Read", change status "New" to "Unread" and migrate data

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#865]
As an attorney,I need a clear indicator of which applications I have Read but I have not given a status update, so that I can find those applications quickly.
![era 1 1](https://cloud.githubusercontent.com/assets/6209366/26324192/a1938c80-3ee6-11e7-8c8b-b3bbb0cd0d9b.png)

**Comment by jennifermarie** [comment]
No data migration needed :) This is all handled in the UI or via the new queries.
