### ISSUE TITLE
Display flash message when returning the user to list after clicking "back" browser button

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#868]
As an attorney, I need clear indicators when an application has moved locations, so that I am not confused when an application disappears from the list and so that I know where to find things that have been marked as "Read".
![era 1 5](https://cloud.githubusercontent.com/assets/6209366/26325103/78dd98ae-3eea-11e7-9ba6-78fb7f6497d1.png)
![era 1 6](https://cloud.githubusercontent.com/assets/6209366/26325105/7be88d92-3eea-11e7-8ab3-16bd8fee0c01.png)

**Comment by jennifermarie** [comment]
Per conversation with Jazmyn, the flash is on the App Detail view.
