### ISSUE TITLE
Serve /favicon.ico

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#872]
The current implementation of favicon does not serve anything at `/favicon.ico`, leading to 404s from agents that do not check the `<head>` which offer paths to various favicons and touch icons.

**Comment by glassresistor** [comment]
I've confirmed that all of the favicons and the browserconfig.xml are in static files and properly linked from the templates. One possibility is that not everypage on our domain is including the <links> in the <head> tag and so those pages are causing the 404s. Another option is its simply some browsers/robots not respecting them.
Its probably good to double check that a static html page or a template file isn't missing the favicon links, so we are not just hiding a legitimate error.
