### ISSUE TITLE
Search autocomplete causes performance issues

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#885]
This was not addressed in #857 

On our autocomplete search functionality we have implemented the search in a quick way that may 
have trouble scaling.

The current situation:
As an authenticated user types out a search term, each key immediately triggers a new AJAX call to the server. When searching for one letter, a huge number of results are returned. If they type another letter, existing AJAX requests are aborted, but the server must still process them.
For example, if I searched for "emily", the javascript would:
1. start a query for "e" (which would include most applications)
2. abort the "e" query and start a query for "em" (still many applications)
3. abort the "em" query and start a query for "emi" 
3. abort the "emi" query and start a query for "emil"
3. abort the "emil" query and start a query for "emily"

In sum, the server would process 5 requests, the first few of which would be quite slow.

Ways this could be improved:
- use a delay before firing a search query request. This way if someone is in the process of typing, we won't fire a search until they stop for a short amount of time.
- paginate results on the server side
- add a loading indicator
- add indexes for fields that we are searching

**Comment by rossettistone** [comment]
Per your idea of reducing the number of requests, this could be an appropriate case for using `lodash`'s `debounce` method. Docs: https://lodash.com/docs/#debounce
