### ISSUE TITLE
Start to scope dev needs for mutli-county partners (like VLSP)

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#912]
VLSP is the first Organization that would serve multiple Counties.
This signals a need to from a many-orgs to one-county relationship towards a many-orgs to many-counties relationship.
In other words, moving from many-to-one, to many-to-many

**Comment by bengolder** [comment]
Immediate thoughts
- Logically, we would need some criteria for deciding where to send an application if there are multiple orgs in the same county. Alameda pub def & EBCLC had a predetermined criteria based on income and assets. An alternative would be to put incoming applicants into a queue that each org can "pull" from.
- currently, the fields required for applying to any given county are based on a form for that specific county. As we rebuild forms, we should be aware of this change. If we do not wish to rebuild the form logic, we would have to create a form that answers the needs of all the orgs in the given county.
- Most other pieces of the code that reference the relation between counties and organizations are used to simply display counties or organizations applied to in the interface.
- an `Application`'s reference to an `Organization` would no longer be sufficient for determining the county that an `Application` pertains to. We could either:
    - add a `county` field to `Application` (so we would have `Application.county` _and_ `Application.organization`
    - have a through table (`CountyOrganization` or `CountyReceiver`, for example) that the `Application` points to, `Application.county_receiver`

**Comment by sarahlizwhite** [comment]
Thanks, Ben! I'll add some comments once I've had longer conversations with both Yolo & VLSP. I like the idea of creating a queue - it's probably a more sustainable solution in the long run but it's also possible VLSP and Public Defenders could have a similar relationship to EBCLC/Alameda. We shall see! :)
