### ISSUE TITLE
Get staticfiles to reload each time

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#913]
I'm having a hard time getting compressor to rebuild static assets in local development.

Here are my current compressor-related settings:
```python
COMPRESS_OFFLINE_TIMEOUT = 0
COMPRESS_JINJA2_GET_ENVIRONMENT = <function COMPRESS_JINJA2_GET_ENVIRONMENT at 0x104310488>
COMPRESS_OFFLINE = False
COMPRESS_ENABLED = True
COMPRESS_PRECOMPILERS = (
    (
        'text/less',
        '/Users/bengolder/projects/clearmyrecord/node_modules/.bin/lessc --include-path=/Users/bengolder/projects/clearmyrecord/node_modules {infile} {outfile}'
    ),
    (
        'text/browserify',
        '/Users/bengolder/projects/clearmyrecord/node_modules/.bin/browserify {infile} -d --outfile {outfile}'
    )
)
```

And the template tag in question:
```html+jinja
    {% compress 'css' %}
      <link rel="stylesheet" type="text/less" href="{{ static('intake/less/main.less') }}">
    {% endcompress %}
```

The dev server is being run with:
```sh
./manage.py runserver
```

**Comment by glassresistor** [comment]
Ok so I've managed to get the static files to reload
First clear out the static files
```
rm -r staticfiles/*
```
Then run runserver without running collectstatic first

```
./manage.py runserver
```

It should now update the less files each time they are changed.  You will also notice the staticfiles directory only has CACHE and no other files.  The solution is just to turn off COMPRESS_OFFILE and not run collectstatic and have an empty staticfiles directory.

**Comment by bengolder** [comment]
This works for me.
