### ISSUE TITLE
Make the mark open section of Application bundles a task

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#926]
[This](
https://github.com/codeforamerica/intake/blob/master/intake/views/admin_views.py#L136-L148) section can be moved into intake/tasks.py, which should greatly speed up the request.

**Comment by bengolder** [comment]
We are deprecating the bundles code this week and next. So while this principle would be useful in a number of places, that task is not particularly high priority. #922

**Comment by glassresistor** [comment]
@bengolder understood i'll removethe bundle portion of #927  then as well
