### ISSUE TITLE
As a CMR support team member, I need to be able to view all CNL submissions and add notes and tags detailing what happened when I contact them, so that I can respond to applicants while being informed of information they've already given us. 

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#931]
To Do: Create Tabbed CMR App Index for "County Not Listed" apps

Functionality:  Whenever we receive a county not listed submission, put those applications into CMR's tabbed app index with fields:
- Data received
- Name
- Preferred contract info
- Counties they listed 
- Notes
- Tags

**Comment by jazmynlatimer** [comment]
![county-not-listed](https://user-images.githubusercontent.com/5255453/26854624-cf970d46-4acb-11e7-9545-3b52649d57d6.jpg)
