### ISSUE TITLE
Use a different URL for linking to new applications page in email notifications

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#946]
So we can track how org users tend to enter the site and view the page.
This can be accomplished through either a GET query parameter, a duplicate URL pointing to the same view, or a URL that redirects to the new apps page.

**Comment by jennifermarie** [comment]
Let's talk about this when we review/merge. Right now, there's a separate URL for unreads -- we can either use this here/throughout or change to a redirect/params.
