### ISSUE TITLE
Setup Downtime and Maintenence Page

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#950]
Use the gcf html to make a downtime page for CMR

Test on Develop and add to Demo and Production

**Comment by glassresistor** [comment]
I've copied over the GCF downtime page for CMR and put it in a bucket
I then set it as cmr-stage 's maintence and error page like so.

heroku config:set ERROR_PAGE_URL=https://s3-us-west-2.amazonaws.com/cmr-maintence-assets/maintenence.html --app cmr-stage
heroku config:set MAINTENANCE_PAGE_URL=https://s3-us-west-2.amazonaws.com/cmr-maintence-assets/maintenence.html --app cmr-stage


If this looks go just run that same command on cmr-demo, cmr-develop, and cmr-prod and add them as variables to app.json so the review apps get it as well.

I've made this branch with the single downtime page file and the updated app.json  https://github.com/codeforamerica/intake/tree/feature/downtime_page

**Comment by glassresistor** [comment]
Including this here with notes for stuff to do next someone gets chance.

This is a shortterm fix and in the future I think we should use [django bakery](http://django-bakery.readthedocs.io/en/latest/gettingstarted.html) to build a static page and publish it to s3.  This will make it easier to style it so it looks more like our original site and will make it easier to update them as needed(and make part of our autodeploy process).

We can either use the same s3 bucket we use to(in the future) publish our other assets or put them in there own bucket.  We can also set compressor to either link directly to the normal css or build it all inline with the page. 

We also need to make a difference downtime page from maintence page which includes different instructions and messaging.  We also need a custom 404 and 500 page for django to serve, which should have similar messaging.

**Comment by joduinn** [comment]
Moving to backlog, while I focus on ClientComm first.

**Comment by joduinn** [comment]
@glassresistor is now back and working on this.

**Comment by glassresistor** [comment]
Got Approval from @jennifermarie and @bengolder to push out the maintence pages as is and to create the other tickets described above.

**Comment by glassresistor** [comment]
All of the Heroku instances now use the same error page for maintence windows and unexpected downtime.

**Comment by glassresistor** [comment]
Created tickets #1002 #1003 #1004
