### ISSUE TITLE
Create an S3 bucket for CMR logs with appropriate permissions

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#953]
An second approach to resolve #873 
https://stackoverflow.com/questions/26016631/send-heroku-logs-to-s3

Discussed in audit hour by @joduinn @jennifermarie @bengolder

Add an S3 bucket with appropriate permissions if it doesn't already exist and adjust papertrail to send archives to that bucket.

**Comment by joduinn** [comment]
During meeting, I read:
http://help.papertrailapp.com/kb/how-it-works/permanent-log-archives/#create-and-share-an-s3-bucket
http://help.papertrailapp.com/kb/how-it-works/automatic-s3-archive-export/

I then did the following:
* logged into the AWS account "Clear My Record"
* created "cmr-log" bucket with write access for papertrail and read/write for infra+cmr@ user but no-one else. All verified access in the meeting.
* In papertrail, I added this s3 bucket and verified that access looked ok to papertrail
* lets wait and see if we get logs tonight at midnight.
* note: this is copying papertrail logs to s3. We still continue to get papertrail logs as usual in heroku, so no risk to current production logs.

<img width="963" alt="screen shot 2017-06-12 at 16 46 04" src="https://user-images.githubusercontent.com/714805/27060031-05dfe568-4f8f-11e7-8c9a-01784101e5a0.png">


cc @bengolder @jennifermarie

**Comment by joduinn** [comment]
@bengolder @jennifermarie 

I've just confirmed that there is a log file posted once-per-day into this "cmr-log" s3 bucket. These log files are not being deleted over time and just accumulate in this s3 bucket. This means we now have logs *without* needing to worry about Heroku's age-off-old-logs tactic.

Closing this ticket with a smile.
