### ISSUE TITLE
"Next" button that submits app is confusing for applicants

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#971]
I talked to an applicant today over the phone who said that when they were applying to SF, they clicked the "Next" button expecting a new page, but the app instead submitted to San Francisco before they were ready. So they called us, left a voicemail and were worried about the app because they weren't ready to apply.

We should maybe change the language on the button to only say next if there are more pages to view before submission.

**Comment by TiffanyAndrews** [comment]
duplicate issue #996
