### ISSUE TITLE
Create alert for bounced emails

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#974]
Sometimes applicants submit with typos/bad email addresses, and our validators are not catching these, which leads to support issues or dropped communications. If we can set an alert when the initial or follow-up email bounces, someone on the CMR team can note the miss and/or try to remedy it.

**Comment by jennifermarie** [comment]
This issue stems from a handful of support emails and bounced follow-up emails, in which it is clear that the user made a typo (misspelling `@gmail.com`, etc.). It seems best not to have to wait until 1 month after the application to handle these.

**Comment by bengolder** [comment]
This would require a significant amount of code to call Front's API, and has been largely addressed by adding validation that prevents input of emails that could bounce.
Closing as low priority.
