### ISSUE TITLE
Add "why are you applying" picklist to Alameda's application 

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/intake#991]
Add this picklist question (spreadsheet has been updated): https://docs.google.com/spreadsheets/d/1RwXX_ZXIq7jqXfllP2QBwXNfvpPAscOOylSl52gOfFk/edit#gid=70218205

Why are you applying to clear your record?
--
To pass a background check,I have a job offer pending,To qualify for housing,Immigration status issues,Was asked to leave job because of my record,End probation early,Homeless or on social services,I have a new case pendingMy reason is not listed

**Comment by TiffanyAndrews** [comment]
UAT: looks good. No changes @lkogler
