### ISSUE TITLE
Research scraping court data

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#994]
As a CMR team member, I need to verify an applicant's petition received a court outcome, so we can confirm clean slate outcome.

**Comment by bengolder** [comment]
Questions a spike should answer:
- Which jurisdictions have data online?
- Which fields are needed for scraping?
- Of those that do, what percentage of applicants are represented there?
- How structured is the data?
- Can we determine court dates?
- Can we determine court outcomes?
- How reliably can the data be parsed?
- How up-to-date is the data?
