### ISSUE TITLE
Change "Next" button to "Submit"

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#996]
Change the "next" button at the bottom of non-Alameda applications with "Submit" 
(Based on applicant feedback via Front)

Alameda requires applicants to write a letter as a final step in their form submission.

Two cases:
 - An applicant has only one form page to fill out.
- an applicant goes to a letter-writing, then a "confirm" page (for reviewing their letter).

Current form flow through views:
- SelectCountyView 
- CountyApplicationView
- (maybe) CountyApplicationNoWarningsView
- (Alameda only) WriteDeclarationLetterView
- (Alameda only) ReviewDeclarationLetterView

**Comment by bengolder** [comment]
This sounds similar to a previous issue:
https://github.com/codeforamerica/intake/issues/971

**Comment by bengolder** [comment]
-  `intake/views/applicant_form_view_base.py` (base that handles pulling session data and final save, or any common rendering context)
-  `intake/views/county_application_view.py`
-  `intake/views/application_done_view.py`
-  `intake/views/declaration_letter_view.py`
- `templates/forms/county_form.jinja`
- `templates/forms/declaration_letter_review.jinja`
- `templates/forms/declaration_letter_review.jinja`

**Comment by loumoore** [comment]
@bengolder seems like needs_declaration_letter is an org-level attribute which is different for Alameda PD vs EBCLC, and we don't know the organization for Alameda until the user fills out the form.  

let me know if i'm missing something, but if this isn't as simple as it looks -- would it be crazy to suggest we just switch 'Next' to 'Submit' always? seems like a really easy fix that will solve the confusion users are having now and wouldn't be a problem in the other direction. we could customize better when we split up the form later and can determine this properly.

lemme know what you think.

**Comment by bengolder** [comment]
@loumoore correct. The copy change encompassed by this ticket would perhaps be better represented as a subtask of https://github.com/codeforamerica/intake/issues/1009
